// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/item.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemView narrows ListItems to a single bucket. ITEM_VIEW_UNSPECIFIED keeps
// the legacy behaviour of returning both active and completed items.
type ItemView int32

const (
	ItemView_ITEM_VIEW_UNSPECIFIED ItemView = 0
	// UNTRIAGED: not done and carrying no manual ordering rank yet.
	ItemView_ITEM_VIEW_UNTRIAGED ItemView = 1
	// TRIAGED: not done and already placed in the manual order.
	ItemView_ITEM_VIEW_TRIAGED ItemView = 2
	// TIME_SENSITIVE: not done and carrying a due date.
	ItemView_ITEM_VIEW_TIME_SENSITIVE ItemView = 3
	// DONE: completed items.
	ItemView_ITEM_VIEW_DONE ItemView = 4
)

// Enum value maps for ItemView.
var (
	ItemView_name = map[int32]string{
		0: "ITEM_VIEW_UNSPECIFIED",
		1: "ITEM_VIEW_UNTRIAGED",
		2: "ITEM_VIEW_TRIAGED",
		3: "ITEM_VIEW_TIME_SENSITIVE",
		4: "ITEM_VIEW_DONE",
	}
	ItemView_value = map[string]int32{
		"ITEM_VIEW_UNSPECIFIED":    0,
		"ITEM_VIEW_UNTRIAGED":      1,
		"ITEM_VIEW_TRIAGED":        2,
		"ITEM_VIEW_TIME_SENSITIVE": 3,
		"ITEM_VIEW_DONE":           4,
	}
)

func (x ItemView) Enum() *ItemView {
	p := new(ItemView)
	*p = x
	return p
}

func (x ItemView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemView) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_item_proto_enumTypes[0].Descriptor()
}

func (ItemView) Type() protoreflect.EnumType {
	return &file_proto_item_proto_enumTypes[0]
}

func (x ItemView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemView.Descriptor instead.
func (ItemView) EnumDescriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{0}
}

// Label is a tag that can be attached to any number of items. Names are
// normalised to lower case with surrounding whitespace removed.
type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Colour        string                 `protobuf:"bytes,3,opt,name=colour,proto3" json:"colour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_proto_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

// Effort is a per-user named level of effort (e.g. "low", "medium", "high").
// An item carries at most one effort. Names are normalised like labels.
type Effort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effort) Reset() {
	*x = Effort{}
	mi := &file_proto_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effort) ProtoMessage() {}

func (x *Effort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effort.ProtoReflect.Descriptor instead.
func (*Effort) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{1}
}

func (x *Effort) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Effort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Blocker is a free-form description of a single blocking reason on an item.
// An item can carry several blockers. The description is stored verbatim: no
// normalisation is applied and duplicates are allowed.
type Blocker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blocker) Reset() {
	*x = Blocker{}
	mi := &file_proto_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blocker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blocker) ProtoMessage() {}

func (x *Blocker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blocker.ProtoReflect.Descriptor instead.
func (*Blocker) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{2}
}

func (x *Blocker) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Blocker) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Comment is a single remark attached to an item. An item can carry several
// comments, ordered by creation. The body is stored verbatim: no
// normalisation is applied. The author is the username of the user that
// created the comment.
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_proto_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{3}
}

func (x *Comment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

// Item is a single todo item.
type Item struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Done        bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	DueDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	ListId      *uint32                `protobuf:"varint,6,opt,name=list_id,json=listId,proto3,oneof" json:"list_id,omitempty"`
	// priority is the manual ordering rank. Higher values sort first. It is set
	// only while done is false and the item has been triaged; untriaged items
	// carry no priority and are excluded from the default listing.
	Priority *float64 `protobuf:"fixed64,7,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	Labels   []*Label `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	// effort is the single effort level attached to the item, if any.
	Effort *Effort `protobuf:"bytes,9,opt,name=effort,proto3" json:"effort,omitempty"`
	// blockers are the distinct blocking reasons attached to the item.
	Blockers []*Blocker `protobuf:"bytes,10,rep,name=blockers,proto3" json:"blockers,omitempty"`
	// linked_items are the items linked to this one. The relationship is
	// symmetric, so a link from A to B appears on B as well.
	LinkedItems []*Item `protobuf:"bytes,11,rep,name=linked_items,json=linkedItems,proto3" json:"linked_items,omitempty"`
	// comments are the remarks attached to the item, in creation order.
	Comments      []*Comment `protobuf:"bytes,12,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{4}
}

func (x *Item) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Item) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Item) GetListId() uint32 {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return 0
}

func (x *Item) GetPriority() float64 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *Item) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Item) GetEffort() *Effort {
	if x != nil {
		return x.Effort
	}
	return nil
}

func (x *Item) GetBlockers() []*Blocker {
	if x != nil {
		return x.Blockers
	}
	return nil
}

func (x *Item) GetLinkedItems() []*Item {
	if x != nil {
		return x.LinkedItems
	}
	return nil
}

func (x *Item) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type ListItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// labels restricts the result to items carrying every one of these labels.
	// An unknown name therefore yields no results.
	Labels []string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	// view narrows the result to a single bucket. Leaving it unset returns both
	// the active and completed items as before.
	View          ItemView `protobuf:"varint,2,opt,name=view,proto3,enum=item.ItemView" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_proto_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{5}
}

func (x *ListItemsRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListItemsRequest) GetView() ItemView {
	if x != nil {
		return x.View
	}
	return ItemView_ITEM_VIEW_UNSPECIFIED
}

type ListItemsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// active holds the items that are not yet done, in manual order.
	Active []*Item `protobuf:"bytes,1,rep,name=active,proto3" json:"active,omitempty"`
	// completed holds the done items, most recently updated first.
	Completed     []*Item `protobuf:"bytes,2,rep,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_proto_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{6}
}

func (x *ListItemsResponse) GetActive() []*Item {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *ListItemsResponse) GetCompleted() []*Item {
	if x != nil {
		return x.Completed
	}
	return nil
}

type CreateItemRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Title       string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DueDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	ListId      *uint32                `protobuf:"varint,4,opt,name=list_id,json=listId,proto3,oneof" json:"list_id,omitempty"`
	// labels are created on the fly when they do not exist yet.
	Labels []string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	// effort is the name of an existing effort to attach to the item. An empty
	// string leaves the item without an effort. Unknown names are reported.
	Effort *string `protobuf:"bytes,6,opt,name=effort,proto3,oneof" json:"effort,omitempty"`
	// link_item_ids are the ids of existing items to link to. The relationship
	// is symmetric. Unknown or cross-user ids are reported; self-links are
	// rejected.
	LinkItemIds   []uint32 `protobuf:"varint,7,rep,packed,name=link_item_ids,json=linkItemIds,proto3" json:"link_item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_proto_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{7}
}

func (x *CreateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateItemRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *CreateItemRequest) GetListId() uint32 {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return 0
}

func (x *CreateItemRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateItemRequest) GetEffort() string {
	if x != nil && x.Effort != nil {
		return *x.Effort
	}
	return ""
}

func (x *CreateItemRequest) GetLinkItemIds() []uint32 {
	if x != nil {
		return x.LinkItemIds
	}
	return nil
}

type MoveItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Exactly one anchor must be supplied.
	//
	// Types that are valid to be assigned to Anchor:
	//
	//	*MoveItemRequest_BeforeId
	//	*MoveItemRequest_AfterId
	//	*MoveItemRequest_Top
	//	*MoveItemRequest_Bottom
	Anchor isMoveItemRequest_Anchor `protobuf_oneof:"anchor"`
	// change_list reports whether list_id should be applied. It distinguishes
	// leaving the list untouched from clearing it.
	ChangeList bool `protobuf:"varint,4,opt,name=change_list,json=changeList,proto3" json:"change_list,omitempty"`
	// list_id is applied only when change_list is true. Leaving it unset while
	// change_list is true detaches the item from its list.
	ListId        *uint32 `protobuf:"varint,5,opt,name=list_id,json=listId,proto3,oneof" json:"list_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveItemRequest) Reset() {
	*x = MoveItemRequest{}
	mi := &file_proto_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveItemRequest) ProtoMessage() {}

func (x *MoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveItemRequest.ProtoReflect.Descriptor instead.
func (*MoveItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{8}
}

func (x *MoveItemRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MoveItemRequest) GetAnchor() isMoveItemRequest_Anchor {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *MoveItemRequest) GetBeforeId() uint32 {
	if x != nil {
		if x, ok := x.Anchor.(*MoveItemRequest_BeforeId); ok {
			return x.BeforeId
		}
	}
	return 0
}

func (x *MoveItemRequest) GetAfterId() uint32 {
	if x != nil {
		if x, ok := x.Anchor.(*MoveItemRequest_AfterId); ok {
			return x.AfterId
		}
	}
	return 0
}

func (x *MoveItemRequest) GetTop() bool {
	if x != nil {
		if x, ok := x.Anchor.(*MoveItemRequest_Top); ok {
			return x.Top
		}
	}
	return false
}

func (x *MoveItemRequest) GetBottom() bool {
	if x != nil {
		if x, ok := x.Anchor.(*MoveItemRequest_Bottom); ok {
			return x.Bottom
		}
	}
	return false
}

func (x *MoveItemRequest) GetChangeList() bool {
	if x != nil {
		return x.ChangeList
	}
	return false
}

func (x *MoveItemRequest) GetListId() uint32 {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return 0
}

type isMoveItemRequest_Anchor interface {
	isMoveItemRequest_Anchor()
}

type MoveItemRequest_BeforeId struct {
	// before_id places the item immediately before the identified item. The
	// anchor must already carry a priority (i.e. be triaged).
	BeforeId uint32 `protobuf:"varint,2,opt,name=before_id,json=beforeId,proto3,oneof"`
}

type MoveItemRequest_AfterId struct {
	// after_id places the item immediately after the identified item. The
	// anchor must already carry a priority (i.e. be triaged).
	AfterId uint32 `protobuf:"varint,3,opt,name=after_id,json=afterId,proto3,oneof"`
}

type MoveItemRequest_Top struct {
	// top assigns the highest priority, used to triage an item when no
	// prioritised anchor exists yet.
	Top bool `protobuf:"varint,6,opt,name=top,proto3,oneof"`
}

type MoveItemRequest_Bottom struct {
	// bottom assigns the lowest priority, used to triage an item when no
	// prioritised anchor exists yet.
	Bottom bool `protobuf:"varint,7,opt,name=bottom,proto3,oneof"`
}

func (*MoveItemRequest_BeforeId) isMoveItemRequest_Anchor() {}

func (*MoveItemRequest_AfterId) isMoveItemRequest_Anchor() {}

func (*MoveItemRequest_Top) isMoveItemRequest_Anchor() {}

func (*MoveItemRequest_Bottom) isMoveItemRequest_Anchor() {}

type SetItemDoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetItemDoneRequest) Reset() {
	*x = SetItemDoneRequest{}
	mi := &file_proto_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetItemDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemDoneRequest) ProtoMessage() {}

func (x *SetItemDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemDoneRequest.ProtoReflect.Descriptor instead.
func (*SetItemDoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{9}
}

func (x *SetItemDoneRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetItemDoneRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type UpdateItemLabelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// add names labels to attach, creating any that do not exist yet.
	Add []string `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty"`
	// remove names labels to detach. Names that are not known labels are
	// ignored rather than being created only to be detached again.
	Remove        []string `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemLabelsRequest) Reset() {
	*x = UpdateItemLabelsRequest{}
	mi := &file_proto_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemLabelsRequest) ProtoMessage() {}

func (x *UpdateItemLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemLabelsRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemLabelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateItemLabelsRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateItemLabelsRequest) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *UpdateItemLabelsRequest) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

type UpdateItemLinksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// add are the ids of items to link to. The relationship is symmetric, so
	// each link also attaches to the target item. Self-links are rejected.
	Add []uint32 `protobuf:"varint,2,rep,packed,name=add,proto3" json:"add,omitempty"`
	// remove are the ids of items to unlink. Removing a link detaches it on
	// both sides.
	Remove        []uint32 `protobuf:"varint,3,rep,packed,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemLinksRequest) Reset() {
	*x = UpdateItemLinksRequest{}
	mi := &file_proto_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemLinksRequest) ProtoMessage() {}

func (x *UpdateItemLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemLinksRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateItemLinksRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateItemLinksRequest) GetAdd() []uint32 {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *UpdateItemLinksRequest) GetRemove() []uint32 {
	if x != nil {
		return x.Remove
	}
	return nil
}

type UpdateItemDueDateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// due_date sets the date when present; leaving it unset clears the date.
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemDueDateRequest) Reset() {
	*x = UpdateItemDueDateRequest{}
	mi := &file_proto_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemDueDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemDueDateRequest) ProtoMessage() {}

func (x *UpdateItemDueDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemDueDateRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemDueDateRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateItemDueDateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateItemDueDateRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

type ListLabelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabelsRequest) Reset() {
	*x = ListLabelsRequest{}
	mi := &file_proto_item_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabelsRequest) ProtoMessage() {}

func (x *ListLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabelsRequest.ProtoReflect.Descriptor instead.
func (*ListLabelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{13}
}

type ListLabelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*Label               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabelsResponse) Reset() {
	*x = ListLabelsResponse{}
	mi := &file_proto_item_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabelsResponse) ProtoMessage() {}

func (x *ListLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabelsResponse.ProtoReflect.Descriptor instead.
func (*ListLabelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{14}
}

func (x *ListLabelsResponse) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Colour        string                 `protobuf:"bytes,2,opt,name=colour,proto3" json:"colour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLabelRequest) Reset() {
	*x = CreateLabelRequest{}
	mi := &file_proto_item_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLabelRequest) ProtoMessage() {}

func (x *CreateLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLabelRequest.ProtoReflect.Descriptor instead.
func (*CreateLabelRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{15}
}

func (x *CreateLabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLabelRequest) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

type RenameLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Colour        *string                `protobuf:"bytes,3,opt,name=colour,proto3,oneof" json:"colour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameLabelRequest) Reset() {
	*x = RenameLabelRequest{}
	mi := &file_proto_item_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameLabelRequest) ProtoMessage() {}

func (x *RenameLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameLabelRequest.ProtoReflect.Descriptor instead.
func (*RenameLabelRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{16}
}

func (x *RenameLabelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RenameLabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RenameLabelRequest) GetColour() string {
	if x != nil && x.Colour != nil {
		return *x.Colour
	}
	return ""
}

type DeleteLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLabelRequest) Reset() {
	*x = DeleteLabelRequest{}
	mi := &file_proto_item_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLabelRequest) ProtoMessage() {}

func (x *DeleteLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLabelRequest.ProtoReflect.Descriptor instead.
func (*DeleteLabelRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteLabelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetItemEffortRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// effort names an existing effort to attach. An empty string clears the
	// item's effort. Unknown names are reported rather than being created.
	Effort        string `protobuf:"bytes,2,opt,name=effort,proto3" json:"effort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetItemEffortRequest) Reset() {
	*x = SetItemEffortRequest{}
	mi := &file_proto_item_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetItemEffortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemEffortRequest) ProtoMessage() {}

func (x *SetItemEffortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemEffortRequest.ProtoReflect.Descriptor instead.
func (*SetItemEffortRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{18}
}

func (x *SetItemEffortRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetItemEffortRequest) GetEffort() string {
	if x != nil {
		return x.Effort
	}
	return ""
}

type ListEffortsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEffortsRequest) Reset() {
	*x = ListEffortsRequest{}
	mi := &file_proto_item_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEffortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEffortsRequest) ProtoMessage() {}

func (x *ListEffortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEffortsRequest.ProtoReflect.Descriptor instead.
func (*ListEffortsRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{19}
}

type ListEffortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Efforts       []*Effort              `protobuf:"bytes,1,rep,name=efforts,proto3" json:"efforts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEffortsResponse) Reset() {
	*x = ListEffortsResponse{}
	mi := &file_proto_item_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEffortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEffortsResponse) ProtoMessage() {}

func (x *ListEffortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEffortsResponse.ProtoReflect.Descriptor instead.
func (*ListEffortsResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{20}
}

func (x *ListEffortsResponse) GetEfforts() []*Effort {
	if x != nil {
		return x.Efforts
	}
	return nil
}

type CreateEffortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEffortRequest) Reset() {
	*x = CreateEffortRequest{}
	mi := &file_proto_item_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEffortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEffortRequest) ProtoMessage() {}

func (x *CreateEffortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEffortRequest.ProtoReflect.Descriptor instead.
func (*CreateEffortRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{21}
}

func (x *CreateEffortRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RenameEffortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameEffortRequest) Reset() {
	*x = RenameEffortRequest{}
	mi := &file_proto_item_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameEffortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameEffortRequest) ProtoMessage() {}

func (x *RenameEffortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameEffortRequest.ProtoReflect.Descriptor instead.
func (*RenameEffortRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{22}
}

func (x *RenameEffortRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RenameEffortRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteEffortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEffortRequest) Reset() {
	*x = DeleteEffortRequest{}
	mi := &file_proto_item_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEffortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEffortRequest) ProtoMessage() {}

func (x *DeleteEffortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEffortRequest.ProtoReflect.Descriptor instead.
func (*DeleteEffortRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteEffortRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListBlockersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockersRequest) Reset() {
	*x = ListBlockersRequest{}
	mi := &file_proto_item_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockersRequest) ProtoMessage() {}

func (x *ListBlockersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockersRequest.ProtoReflect.Descriptor instead.
func (*ListBlockersRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{24}
}

func (x *ListBlockersRequest) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type ListBlockersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blockers      []*Blocker             `protobuf:"bytes,1,rep,name=blockers,proto3" json:"blockers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockersResponse) Reset() {
	*x = ListBlockersResponse{}
	mi := &file_proto_item_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockersResponse) ProtoMessage() {}

func (x *ListBlockersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockersResponse.ProtoReflect.Descriptor instead.
func (*ListBlockersResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{25}
}

func (x *ListBlockersResponse) GetBlockers() []*Blocker {
	if x != nil {
		return x.Blockers
	}
	return nil
}

type CreateBlockerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlockerRequest) Reset() {
	*x = CreateBlockerRequest{}
	mi := &file_proto_item_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlockerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlockerRequest) ProtoMessage() {}

func (x *CreateBlockerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlockerRequest.ProtoReflect.Descriptor instead.
func (*CreateBlockerRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{26}
}

func (x *CreateBlockerRequest) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CreateBlockerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateBlockerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlockerRequest) Reset() {
	*x = UpdateBlockerRequest{}
	mi := &file_proto_item_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlockerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlockerRequest) ProtoMessage() {}

func (x *UpdateBlockerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlockerRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlockerRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateBlockerRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBlockerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteBlockerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlockerRequest) Reset() {
	*x = DeleteBlockerRequest{}
	mi := &file_proto_item_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlockerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockerRequest) ProtoMessage() {}

func (x *DeleteBlockerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockerRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlockerRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteBlockerRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_proto_item_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{29}
}

func (x *ListCommentsRequest) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_proto_item_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{30}
}

func (x *ListCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_proto_item_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{31}
}

func (x *CreateCommentRequest) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CreateCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_proto_item_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateCommentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_proto_item_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteCommentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_item_proto protoreflect.FileDescriptor

const file_proto_item_proto_rawDesc = "" +
	"\n" +
	"\x10proto/item.proto\x12\x04item\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x05Label\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06colour\x18\x03 \x01(\tR\x06colour\",\n" +
	"\x06Effort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\";\n" +
	"\aBlocker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x80\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\"\xd3\x03\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12:\n" +
	"\bdue_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\adueDate\x88\x01\x01\x12\x1c\n" +
	"\alist_id\x18\x06 \x01(\rH\x01R\x06listId\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\a \x01(\x01H\x02R\bpriority\x88\x01\x01\x12#\n" +
	"\x06labels\x18\b \x03(\v2\v.item.LabelR\x06labels\x12$\n" +
	"\x06effort\x18\t \x01(\v2\f.item.EffortR\x06effort\x12)\n" +
	"\bblockers\x18\n" +
	" \x03(\v2\r.item.BlockerR\bblockers\x12-\n" +
	"\flinked_items\x18\v \x03(\v2\n" +
	".item.ItemR\vlinkedItems\x12)\n" +
	"\bcomments\x18\f \x03(\v2\r.item.CommentR\bcommentsB\v\n" +
	"\t_due_dateB\n" +
	"\n" +
	"\b_list_idB\v\n" +
	"\t_priority\"N\n" +
	"\x10ListItemsRequest\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\tR\x06labels\x12\"\n" +
	"\x04view\x18\x02 \x01(\x0e2\x0e.item.ItemViewR\x04view\"a\n" +
	"\x11ListItemsResponse\x12\"\n" +
	"\x06active\x18\x01 \x03(\v2\n" +
	".item.ItemR\x06active\x12(\n" +
	"\tcompleted\x18\x02 \x03(\v2\n" +
	".item.ItemR\tcompleted\"\xa2\x02\n" +
	"\x11CreateItemRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\bdue_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\adueDate\x88\x01\x01\x12\x1c\n" +
	"\alist_id\x18\x04 \x01(\rH\x01R\x06listId\x88\x01\x01\x12\x16\n" +
	"\x06labels\x18\x05 \x03(\tR\x06labels\x12\x1b\n" +
	"\x06effort\x18\x06 \x01(\tH\x02R\x06effort\x88\x01\x01\x12\"\n" +
	"\rlink_item_ids\x18\a \x03(\rR\vlinkItemIdsB\v\n" +
	"\t_due_dateB\n" +
	"\n" +
	"\b_list_idB\t\n" +
	"\a_effort\"\xe0\x01\n" +
	"\x0fMoveItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\tbefore_id\x18\x02 \x01(\rH\x00R\bbeforeId\x12\x1b\n" +
	"\bafter_id\x18\x03 \x01(\rH\x00R\aafterId\x12\x12\n" +
	"\x03top\x18\x06 \x01(\bH\x00R\x03top\x12\x18\n" +
	"\x06bottom\x18\a \x01(\bH\x00R\x06bottom\x12\x1f\n" +
	"\vchange_list\x18\x04 \x01(\bR\n" +
	"changeList\x12\x1c\n" +
	"\alist_id\x18\x05 \x01(\rH\x01R\x06listId\x88\x01\x01B\b\n" +
	"\x06anchorB\n" +
	"\n" +
	"\b_list_id\"8\n" +
	"\x12SetItemDoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\"S\n" +
	"\x17UpdateItemLabelsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03add\x18\x02 \x03(\tR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\"R\n" +
	"\x16UpdateItemLinksRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03add\x18\x02 \x03(\rR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\rR\x06remove\"s\n" +
	"\x18UpdateItemDueDateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12:\n" +
	"\bdue_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\adueDate\x88\x01\x01B\v\n" +
	"\t_due_date\"\x13\n" +
	"\x11ListLabelsRequest\"9\n" +
	"\x12ListLabelsResponse\x12#\n" +
	"\x06labels\x18\x01 \x03(\v2\v.item.LabelR\x06labels\"@\n" +
	"\x12CreateLabelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06colour\x18\x02 \x01(\tR\x06colour\"`\n" +
	"\x12RenameLabelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\x06colour\x18\x03 \x01(\tH\x00R\x06colour\x88\x01\x01B\t\n" +
	"\a_colour\"$\n" +
	"\x12DeleteLabelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\">\n" +
	"\x14SetItemEffortRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06effort\x18\x02 \x01(\tR\x06effort\"\x14\n" +
	"\x12ListEffortsRequest\"=\n" +
	"\x13ListEffortsResponse\x12&\n" +
	"\aefforts\x18\x01 \x03(\v2\f.item.EffortR\aefforts\")\n" +
	"\x13CreateEffortRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\x13RenameEffortRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"%\n" +
	"\x13DeleteEffortRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\".\n" +
	"\x13ListBlockersRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\"A\n" +
	"\x14ListBlockersResponse\x12)\n" +
	"\bblockers\x18\x01 \x03(\v2\r.item.BlockerR\bblockers\"Q\n" +
	"\x14CreateBlockerRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"H\n" +
	"\x14UpdateBlockerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"&\n" +
	"\x14DeleteBlockerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\".\n" +
	"\x13ListCommentsRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\"A\n" +
	"\x14ListCommentsResponse\x12)\n" +
	"\bcomments\x18\x01 \x03(\v2\r.item.CommentR\bcomments\"C\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\":\n" +
	"\x14UpdateCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"&\n" +
	"\x14DeleteCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id*\x87\x01\n" +
	"\bItemView\x12\x19\n" +
	"\x15ITEM_VIEW_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ITEM_VIEW_UNTRIAGED\x10\x01\x12\x15\n" +
	"\x11ITEM_VIEW_TRIAGED\x10\x02\x12\x1c\n" +
	"\x18ITEM_VIEW_TIME_SENSITIVE\x10\x03\x12\x12\n" +
	"\x0eITEM_VIEW_DONE\x10\x042\xc7\v\n" +
	"\vItemService\x12<\n" +
	"\tListItems\x12\x16.item.ListItemsRequest\x1a\x17.item.ListItemsResponse\x121\n" +
	"\n" +
	"CreateItem\x12\x17.item.CreateItemRequest\x1a\n" +
	".item.Item\x12-\n" +
	"\bMoveItem\x12\x15.item.MoveItemRequest\x1a\n" +
	".item.Item\x123\n" +
	"\vSetItemDone\x12\x18.item.SetItemDoneRequest\x1a\n" +
	".item.Item\x12=\n" +
	"\x10UpdateItemLabels\x12\x1d.item.UpdateItemLabelsRequest\x1a\n" +
	".item.Item\x12;\n" +
	"\x0fUpdateItemLinks\x12\x1c.item.UpdateItemLinksRequest\x1a\n" +
	".item.Item\x12?\n" +
	"\x11UpdateItemDueDate\x12\x1e.item.UpdateItemDueDateRequest\x1a\n" +
	".item.Item\x127\n" +
	"\rSetItemEffort\x12\x1a.item.SetItemEffortRequest\x1a\n" +
	".item.Item\x12?\n" +
	"\n" +
	"ListLabels\x12\x17.item.ListLabelsRequest\x1a\x18.item.ListLabelsResponse\x124\n" +
	"\vCreateLabel\x12\x18.item.CreateLabelRequest\x1a\v.item.Label\x124\n" +
	"\vRenameLabel\x12\x18.item.RenameLabelRequest\x1a\v.item.Label\x12?\n" +
	"\vDeleteLabel\x12\x18.item.DeleteLabelRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\vListEfforts\x12\x18.item.ListEffortsRequest\x1a\x19.item.ListEffortsResponse\x127\n" +
	"\fCreateEffort\x12\x19.item.CreateEffortRequest\x1a\f.item.Effort\x127\n" +
	"\fRenameEffort\x12\x19.item.RenameEffortRequest\x1a\f.item.Effort\x12A\n" +
	"\fDeleteEffort\x12\x19.item.DeleteEffortRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\fListBlockers\x12\x19.item.ListBlockersRequest\x1a\x1a.item.ListBlockersResponse\x12:\n" +
	"\rCreateBlocker\x12\x1a.item.CreateBlockerRequest\x1a\r.item.Blocker\x12:\n" +
	"\rUpdateBlocker\x12\x1a.item.UpdateBlockerRequest\x1a\r.item.Blocker\x12C\n" +
	"\rDeleteBlocker\x12\x1a.item.DeleteBlockerRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\fListComments\x12\x19.item.ListCommentsRequest\x1a\x1a.item.ListCommentsResponse\x12:\n" +
	"\rCreateComment\x12\x1a.item.CreateCommentRequest\x1a\r.item.Comment\x12:\n" +
	"\rUpdateComment\x12\x1a.item.UpdateCommentRequest\x1a\r.item.Comment\x12C\n" +
	"\rDeleteComment\x12\x1a.item.DeleteCommentRequest\x1a\x16.google.protobuf.EmptyB$Z\"github.com/alexhokl/todo-cli/protob\x06proto3"

var (
	file_proto_item_proto_rawDescOnce sync.Once
	file_proto_item_proto_rawDescData []byte
)

func file_proto_item_proto_rawDescGZIP() []byte {
	file_proto_item_proto_rawDescOnce.Do(func() {
		file_proto_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_item_proto_rawDesc), len(file_proto_item_proto_rawDesc)))
	})
	return file_proto_item_proto_rawDescData
}

var file_proto_item_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_item_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_proto_item_proto_goTypes = []any{
	(ItemView)(0),                    // 0: item.ItemView
	(*Label)(nil),                    // 1: item.Label
	(*Effort)(nil),                   // 2: item.Effort
	(*Blocker)(nil),                  // 3: item.Blocker
	(*Comment)(nil),                  // 4: item.Comment
	(*Item)(nil),                     // 5: item.Item
	(*ListItemsRequest)(nil),         // 6: item.ListItemsRequest
	(*ListItemsResponse)(nil),        // 7: item.ListItemsResponse
	(*CreateItemRequest)(nil),        // 8: item.CreateItemRequest
	(*MoveItemRequest)(nil),          // 9: item.MoveItemRequest
	(*SetItemDoneRequest)(nil),       // 10: item.SetItemDoneRequest
	(*UpdateItemLabelsRequest)(nil),  // 11: item.UpdateItemLabelsRequest
	(*UpdateItemLinksRequest)(nil),   // 12: item.UpdateItemLinksRequest
	(*UpdateItemDueDateRequest)(nil), // 13: item.UpdateItemDueDateRequest
	(*ListLabelsRequest)(nil),        // 14: item.ListLabelsRequest
	(*ListLabelsResponse)(nil),       // 15: item.ListLabelsResponse
	(*CreateLabelRequest)(nil),       // 16: item.CreateLabelRequest
	(*RenameLabelRequest)(nil),       // 17: item.RenameLabelRequest
	(*DeleteLabelRequest)(nil),       // 18: item.DeleteLabelRequest
	(*SetItemEffortRequest)(nil),     // 19: item.SetItemEffortRequest
	(*ListEffortsRequest)(nil),       // 20: item.ListEffortsRequest
	(*ListEffortsResponse)(nil),      // 21: item.ListEffortsResponse
	(*CreateEffortRequest)(nil),      // 22: item.CreateEffortRequest
	(*RenameEffortRequest)(nil),      // 23: item.RenameEffortRequest
	(*DeleteEffortRequest)(nil),      // 24: item.DeleteEffortRequest
	(*ListBlockersRequest)(nil),      // 25: item.ListBlockersRequest
	(*ListBlockersResponse)(nil),     // 26: item.ListBlockersResponse
	(*CreateBlockerRequest)(nil),     // 27: item.CreateBlockerRequest
	(*UpdateBlockerRequest)(nil),     // 28: item.UpdateBlockerRequest
	(*DeleteBlockerRequest)(nil),     // 29: item.DeleteBlockerRequest
	(*ListCommentsRequest)(nil),      // 30: item.ListCommentsRequest
	(*ListCommentsResponse)(nil),     // 31: item.ListCommentsResponse
	(*CreateCommentRequest)(nil),     // 32: item.CreateCommentRequest
	(*UpdateCommentRequest)(nil),     // 33: item.UpdateCommentRequest
	(*DeleteCommentRequest)(nil),     // 34: item.DeleteCommentRequest
	(*timestamppb.Timestamp)(nil),    // 35: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 36: google.protobuf.Empty
}
var file_proto_item_proto_depIdxs = []int32{
	35, // 0: item.Comment.created_at:type_name -> google.protobuf.Timestamp
	35, // 1: item.Item.due_date:type_name -> google.protobuf.Timestamp
	1,  // 2: item.Item.labels:type_name -> item.Label
	2,  // 3: item.Item.effort:type_name -> item.Effort
	3,  // 4: item.Item.blockers:type_name -> item.Blocker
	5,  // 5: item.Item.linked_items:type_name -> item.Item
	4,  // 6: item.Item.comments:type_name -> item.Comment
	0,  // 7: item.ListItemsRequest.view:type_name -> item.ItemView
	5,  // 8: item.ListItemsResponse.active:type_name -> item.Item
	5,  // 9: item.ListItemsResponse.completed:type_name -> item.Item
	35, // 10: item.CreateItemRequest.due_date:type_name -> google.protobuf.Timestamp
	35, // 11: item.UpdateItemDueDateRequest.due_date:type_name -> google.protobuf.Timestamp
	1,  // 12: item.ListLabelsResponse.labels:type_name -> item.Label
	2,  // 13: item.ListEffortsResponse.efforts:type_name -> item.Effort
	3,  // 14: item.ListBlockersResponse.blockers:type_name -> item.Blocker
	4,  // 15: item.ListCommentsResponse.comments:type_name -> item.Comment
	6,  // 16: item.ItemService.ListItems:input_type -> item.ListItemsRequest
	8,  // 17: item.ItemService.CreateItem:input_type -> item.CreateItemRequest
	9,  // 18: item.ItemService.MoveItem:input_type -> item.MoveItemRequest
	10, // 19: item.ItemService.SetItemDone:input_type -> item.SetItemDoneRequest
	11, // 20: item.ItemService.UpdateItemLabels:input_type -> item.UpdateItemLabelsRequest
	12, // 21: item.ItemService.UpdateItemLinks:input_type -> item.UpdateItemLinksRequest
	13, // 22: item.ItemService.UpdateItemDueDate:input_type -> item.UpdateItemDueDateRequest
	19, // 23: item.ItemService.SetItemEffort:input_type -> item.SetItemEffortRequest
	14, // 24: item.ItemService.ListLabels:input_type -> item.ListLabelsRequest
	16, // 25: item.ItemService.CreateLabel:input_type -> item.CreateLabelRequest
	17, // 26: item.ItemService.RenameLabel:input_type -> item.RenameLabelRequest
	18, // 27: item.ItemService.DeleteLabel:input_type -> item.DeleteLabelRequest
	20, // 28: item.ItemService.ListEfforts:input_type -> item.ListEffortsRequest
	22, // 29: item.ItemService.CreateEffort:input_type -> item.CreateEffortRequest
	23, // 30: item.ItemService.RenameEffort:input_type -> item.RenameEffortRequest
	24, // 31: item.ItemService.DeleteEffort:input_type -> item.DeleteEffortRequest
	25, // 32: item.ItemService.ListBlockers:input_type -> item.ListBlockersRequest
	27, // 33: item.ItemService.CreateBlocker:input_type -> item.CreateBlockerRequest
	28, // 34: item.ItemService.UpdateBlocker:input_type -> item.UpdateBlockerRequest
	29, // 35: item.ItemService.DeleteBlocker:input_type -> item.DeleteBlockerRequest
	30, // 36: item.ItemService.ListComments:input_type -> item.ListCommentsRequest
	32, // 37: item.ItemService.CreateComment:input_type -> item.CreateCommentRequest
	33, // 38: item.ItemService.UpdateComment:input_type -> item.UpdateCommentRequest
	34, // 39: item.ItemService.DeleteComment:input_type -> item.DeleteCommentRequest
	7,  // 40: item.ItemService.ListItems:output_type -> item.ListItemsResponse
	5,  // 41: item.ItemService.CreateItem:output_type -> item.Item
	5,  // 42: item.ItemService.MoveItem:output_type -> item.Item
	5,  // 43: item.ItemService.SetItemDone:output_type -> item.Item
	5,  // 44: item.ItemService.UpdateItemLabels:output_type -> item.Item
	5,  // 45: item.ItemService.UpdateItemLinks:output_type -> item.Item
	5,  // 46: item.ItemService.UpdateItemDueDate:output_type -> item.Item
	5,  // 47: item.ItemService.SetItemEffort:output_type -> item.Item
	15, // 48: item.ItemService.ListLabels:output_type -> item.ListLabelsResponse
	1,  // 49: item.ItemService.CreateLabel:output_type -> item.Label
	1,  // 50: item.ItemService.RenameLabel:output_type -> item.Label
	36, // 51: item.ItemService.DeleteLabel:output_type -> google.protobuf.Empty
	21, // 52: item.ItemService.ListEfforts:output_type -> item.ListEffortsResponse
	2,  // 53: item.ItemService.CreateEffort:output_type -> item.Effort
	2,  // 54: item.ItemService.RenameEffort:output_type -> item.Effort
	36, // 55: item.ItemService.DeleteEffort:output_type -> google.protobuf.Empty
	26, // 56: item.ItemService.ListBlockers:output_type -> item.ListBlockersResponse
	3,  // 57: item.ItemService.CreateBlocker:output_type -> item.Blocker
	3,  // 58: item.ItemService.UpdateBlocker:output_type -> item.Blocker
	36, // 59: item.ItemService.DeleteBlocker:output_type -> google.protobuf.Empty
	31, // 60: item.ItemService.ListComments:output_type -> item.ListCommentsResponse
	4,  // 61: item.ItemService.CreateComment:output_type -> item.Comment
	4,  // 62: item.ItemService.UpdateComment:output_type -> item.Comment
	36, // 63: item.ItemService.DeleteComment:output_type -> google.protobuf.Empty
	40, // [40:64] is the sub-list for method output_type
	16, // [16:40] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_item_proto_init() }
func file_proto_item_proto_init() {
	if File_proto_item_proto != nil {
		return
	}
	file_proto_item_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_item_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_item_proto_msgTypes[8].OneofWrappers = []any{
		(*MoveItemRequest_BeforeId)(nil),
		(*MoveItemRequest_AfterId)(nil),
		(*MoveItemRequest_Top)(nil),
		(*MoveItemRequest_Bottom)(nil),
	}
	file_proto_item_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_item_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_item_proto_rawDesc), len(file_proto_item_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_item_proto_goTypes,
		DependencyIndexes: file_proto_item_proto_depIdxs,
		EnumInfos:         file_proto_item_proto_enumTypes,
		MessageInfos:      file_proto_item_proto_msgTypes,
	}.Build()
	File_proto_item_proto = out.File
	file_proto_item_proto_goTypes = nil
	file_proto_item_proto_depIdxs = nil
}
