// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/item.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemService_ListItems_FullMethodName         = "/item.ItemService/ListItems"
	ItemService_CreateItem_FullMethodName        = "/item.ItemService/CreateItem"
	ItemService_GetItem_FullMethodName           = "/item.ItemService/GetItem"
	ItemService_MoveItem_FullMethodName          = "/item.ItemService/MoveItem"
	ItemService_SetItemDone_FullMethodName       = "/item.ItemService/SetItemDone"
	ItemService_UpdateItemLabels_FullMethodName  = "/item.ItemService/UpdateItemLabels"
	ItemService_UpdateItemLinks_FullMethodName   = "/item.ItemService/UpdateItemLinks"
	ItemService_UpdateItemDueDate_FullMethodName = "/item.ItemService/UpdateItemDueDate"
	ItemService_SetItemEffort_FullMethodName     = "/item.ItemService/SetItemEffort"
	ItemService_ListLabels_FullMethodName        = "/item.ItemService/ListLabels"
	ItemService_CreateLabel_FullMethodName       = "/item.ItemService/CreateLabel"
	ItemService_RenameLabel_FullMethodName       = "/item.ItemService/RenameLabel"
	ItemService_DeleteLabel_FullMethodName       = "/item.ItemService/DeleteLabel"
	ItemService_ListEfforts_FullMethodName       = "/item.ItemService/ListEfforts"
	ItemService_CreateEffort_FullMethodName      = "/item.ItemService/CreateEffort"
	ItemService_RenameEffort_FullMethodName      = "/item.ItemService/RenameEffort"
	ItemService_DeleteEffort_FullMethodName      = "/item.ItemService/DeleteEffort"
	ItemService_ListBlockers_FullMethodName      = "/item.ItemService/ListBlockers"
	ItemService_CreateBlocker_FullMethodName     = "/item.ItemService/CreateBlocker"
	ItemService_UpdateBlocker_FullMethodName     = "/item.ItemService/UpdateBlocker"
	ItemService_DeleteBlocker_FullMethodName     = "/item.ItemService/DeleteBlocker"
	ItemService_ListComments_FullMethodName      = "/item.ItemService/ListComments"
	ItemService_CreateComment_FullMethodName     = "/item.ItemService/CreateComment"
	ItemService_UpdateComment_FullMethodName     = "/item.ItemService/UpdateComment"
	ItemService_DeleteComment_FullMethodName     = "/item.ItemService/DeleteComment"
)

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ItemService is the gRPC API served by `todo serve`. RPCs are added here and
// registered in cmd/serve.go.
type ItemServiceClient interface {
	// ListItems returns the active items in their manual order along with the
	// completed items ordered by how recently they were updated.
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	// CreateItem appends a new item to the end of the manual order.
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*Item, error)
	// GetItem returns a single item by identifier.
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*Item, error)
	// MoveItem places an item immediately before or after another item and
	// optionally reassigns its list in the same operation.
	MoveItem(ctx context.Context, in *MoveItemRequest, opts ...grpc.CallOption) (*Item, error)
	// SetItemDone completes or reopens an item. Completing removes it from the
	// manual order; reopening appends it to the end.
	SetItemDone(ctx context.Context, in *SetItemDoneRequest, opts ...grpc.CallOption) (*Item, error)
	// UpdateItemLabels attaches and detaches labels on an item. Labels being
	// added are created on the fly when they do not exist yet.
	UpdateItemLabels(ctx context.Context, in *UpdateItemLabelsRequest, opts ...grpc.CallOption) (*Item, error)
	// UpdateItemLinks attaches and detaches links between an item and other
	// items. The relationship is symmetric: linking A to B also links B to A.
	UpdateItemLinks(ctx context.Context, in *UpdateItemLinksRequest, opts ...grpc.CallOption) (*Item, error)
	// UpdateItemDueDate sets or clears an item's due date.
	UpdateItemDueDate(ctx context.Context, in *UpdateItemDueDateRequest, opts ...grpc.CallOption) (*Item, error)
	// SetItemEffort attaches an effort to an item by name, or clears it when the
	// name is empty. The effort must already exist; unknown names are reported.
	SetItemEffort(ctx context.Context, in *SetItemEffortRequest, opts ...grpc.CallOption) (*Item, error)
	// ListLabels returns every known label ordered by name.
	ListLabels(ctx context.Context, in *ListLabelsRequest, opts ...grpc.CallOption) (*ListLabelsResponse, error)
	// CreateLabel creates a label explicitly and reports a name that is already
	// taken rather than returning the existing label.
	CreateLabel(ctx context.Context, in *CreateLabelRequest, opts ...grpc.CallOption) (*Label, error)
	// RenameLabel changes the name of an existing label.
	RenameLabel(ctx context.Context, in *RenameLabelRequest, opts ...grpc.CallOption) (*Label, error)
	// DeleteLabel removes a label that is no longer attached to any item.
	DeleteLabel(ctx context.Context, in *DeleteLabelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListEfforts returns every known effort ordered by name.
	ListEfforts(ctx context.Context, in *ListEffortsRequest, opts ...grpc.CallOption) (*ListEffortsResponse, error)
	// CreateEffort creates an effort explicitly and reports a name that is
	// already taken rather than returning the existing effort.
	CreateEffort(ctx context.Context, in *CreateEffortRequest, opts ...grpc.CallOption) (*Effort, error)
	// RenameEffort changes the name of an existing effort.
	RenameEffort(ctx context.Context, in *RenameEffortRequest, opts ...grpc.CallOption) (*Effort, error)
	// DeleteEffort removes an effort that is no longer attached to any item.
	DeleteEffort(ctx context.Context, in *DeleteEffortRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListBlockers returns every blocker attached to the given item, ordered by
	// identifier.
	ListBlockers(ctx context.Context, in *ListBlockersRequest, opts ...grpc.CallOption) (*ListBlockersResponse, error)
	// CreateBlocker attaches a new blocker to an item.
	CreateBlocker(ctx context.Context, in *CreateBlockerRequest, opts ...grpc.CallOption) (*Blocker, error)
	// UpdateBlocker changes the description of an existing blocker.
	UpdateBlocker(ctx context.Context, in *UpdateBlockerRequest, opts ...grpc.CallOption) (*Blocker, error)
	// DeleteBlocker removes a blocker.
	DeleteBlocker(ctx context.Context, in *DeleteBlockerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListComments returns every comment attached to the given item, ordered by
	// identifier (creation order).
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	// CreateComment attaches a new comment to an item.
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	// UpdateComment edits the body of an existing comment.
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	// DeleteComment removes a comment.
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type itemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemServiceClient(cc grpc.ClientConnInterface) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, ItemService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_CreateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) MoveItem(ctx context.Context, in *MoveItemRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_MoveItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) SetItemDone(ctx context.Context, in *SetItemDoneRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_SetItemDone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) UpdateItemLabels(ctx context.Context, in *UpdateItemLabelsRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_UpdateItemLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) UpdateItemLinks(ctx context.Context, in *UpdateItemLinksRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_UpdateItemLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) UpdateItemDueDate(ctx context.Context, in *UpdateItemDueDateRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_UpdateItemDueDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) SetItemEffort(ctx context.Context, in *SetItemEffortRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_SetItemEffort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ListLabels(ctx context.Context, in *ListLabelsRequest, opts ...grpc.CallOption) (*ListLabelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLabelsResponse)
	err := c.cc.Invoke(ctx, ItemService_ListLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) CreateLabel(ctx context.Context, in *CreateLabelRequest, opts ...grpc.CallOption) (*Label, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Label)
	err := c.cc.Invoke(ctx, ItemService_CreateLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) RenameLabel(ctx context.Context, in *RenameLabelRequest, opts ...grpc.CallOption) (*Label, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Label)
	err := c.cc.Invoke(ctx, ItemService_RenameLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) DeleteLabel(ctx context.Context, in *DeleteLabelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ItemService_DeleteLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ListEfforts(ctx context.Context, in *ListEffortsRequest, opts ...grpc.CallOption) (*ListEffortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEffortsResponse)
	err := c.cc.Invoke(ctx, ItemService_ListEfforts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) CreateEffort(ctx context.Context, in *CreateEffortRequest, opts ...grpc.CallOption) (*Effort, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Effort)
	err := c.cc.Invoke(ctx, ItemService_CreateEffort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) RenameEffort(ctx context.Context, in *RenameEffortRequest, opts ...grpc.CallOption) (*Effort, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Effort)
	err := c.cc.Invoke(ctx, ItemService_RenameEffort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) DeleteEffort(ctx context.Context, in *DeleteEffortRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ItemService_DeleteEffort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ListBlockers(ctx context.Context, in *ListBlockersRequest, opts ...grpc.CallOption) (*ListBlockersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlockersResponse)
	err := c.cc.Invoke(ctx, ItemService_ListBlockers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) CreateBlocker(ctx context.Context, in *CreateBlockerRequest, opts ...grpc.CallOption) (*Blocker, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Blocker)
	err := c.cc.Invoke(ctx, ItemService_CreateBlocker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) UpdateBlocker(ctx context.Context, in *UpdateBlockerRequest, opts ...grpc.CallOption) (*Blocker, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Blocker)
	err := c.cc.Invoke(ctx, ItemService_UpdateBlocker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) DeleteBlocker(ctx context.Context, in *DeleteBlockerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ItemService_DeleteBlocker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, ItemService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comment)
	err := c.cc.Invoke(ctx, ItemService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comment)
	err := c.cc.Invoke(ctx, ItemService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ItemService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
// All implementations must embed UnimplementedItemServiceServer
// for forward compatibility.
//
// ItemService is the gRPC API served by `todo serve`. RPCs are added here and
// registered in cmd/serve.go.
type ItemServiceServer interface {
	// ListItems returns the active items in their manual order along with the
	// completed items ordered by how recently they were updated.
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	// CreateItem appends a new item to the end of the manual order.
	CreateItem(context.Context, *CreateItemRequest) (*Item, error)
	// GetItem returns a single item by identifier.
	GetItem(context.Context, *GetItemRequest) (*Item, error)
	// MoveItem places an item immediately before or after another item and
	// optionally reassigns its list in the same operation.
	MoveItem(context.Context, *MoveItemRequest) (*Item, error)
	// SetItemDone completes or reopens an item. Completing removes it from the
	// manual order; reopening appends it to the end.
	SetItemDone(context.Context, *SetItemDoneRequest) (*Item, error)
	// UpdateItemLabels attaches and detaches labels on an item. Labels being
	// added are created on the fly when they do not exist yet.
	UpdateItemLabels(context.Context, *UpdateItemLabelsRequest) (*Item, error)
	// UpdateItemLinks attaches and detaches links between an item and other
	// items. The relationship is symmetric: linking A to B also links B to A.
	UpdateItemLinks(context.Context, *UpdateItemLinksRequest) (*Item, error)
	// UpdateItemDueDate sets or clears an item's due date.
	UpdateItemDueDate(context.Context, *UpdateItemDueDateRequest) (*Item, error)
	// SetItemEffort attaches an effort to an item by name, or clears it when the
	// name is empty. The effort must already exist; unknown names are reported.
	SetItemEffort(context.Context, *SetItemEffortRequest) (*Item, error)
	// ListLabels returns every known label ordered by name.
	ListLabels(context.Context, *ListLabelsRequest) (*ListLabelsResponse, error)
	// CreateLabel creates a label explicitly and reports a name that is already
	// taken rather than returning the existing label.
	CreateLabel(context.Context, *CreateLabelRequest) (*Label, error)
	// RenameLabel changes the name of an existing label.
	RenameLabel(context.Context, *RenameLabelRequest) (*Label, error)
	// DeleteLabel removes a label that is no longer attached to any item.
	DeleteLabel(context.Context, *DeleteLabelRequest) (*emptypb.Empty, error)
	// ListEfforts returns every known effort ordered by name.
	ListEfforts(context.Context, *ListEffortsRequest) (*ListEffortsResponse, error)
	// CreateEffort creates an effort explicitly and reports a name that is
	// already taken rather than returning the existing effort.
	CreateEffort(context.Context, *CreateEffortRequest) (*Effort, error)
	// RenameEffort changes the name of an existing effort.
	RenameEffort(context.Context, *RenameEffortRequest) (*Effort, error)
	// DeleteEffort removes an effort that is no longer attached to any item.
	DeleteEffort(context.Context, *DeleteEffortRequest) (*emptypb.Empty, error)
	// ListBlockers returns every blocker attached to the given item, ordered by
	// identifier.
	ListBlockers(context.Context, *ListBlockersRequest) (*ListBlockersResponse, error)
	// CreateBlocker attaches a new blocker to an item.
	CreateBlocker(context.Context, *CreateBlockerRequest) (*Blocker, error)
	// UpdateBlocker changes the description of an existing blocker.
	UpdateBlocker(context.Context, *UpdateBlockerRequest) (*Blocker, error)
	// DeleteBlocker removes a blocker.
	DeleteBlocker(context.Context, *DeleteBlockerRequest) (*emptypb.Empty, error)
	// ListComments returns every comment attached to the given item, ordered by
	// identifier (creation order).
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	// CreateComment attaches a new comment to an item.
	CreateComment(context.Context, *CreateCommentRequest) (*Comment, error)
	// UpdateComment edits the body of an existing comment.
	UpdateComment(context.Context, *UpdateCommentRequest) (*Comment, error)
	// DeleteComment removes a comment.
	DeleteComment(context.Context, *DeleteCommentRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedItemServiceServer()
}

// UnimplementedItemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemServiceServer struct{}

func (UnimplementedItemServiceServer) ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedItemServiceServer) CreateItem(context.Context, *CreateItemRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedItemServiceServer) GetItem(context.Context, *GetItemRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedItemServiceServer) MoveItem(context.Context, *MoveItemRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveItem not implemented")
}
func (UnimplementedItemServiceServer) SetItemDone(context.Context, *SetItemDoneRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method SetItemDone not implemented")
}
func (UnimplementedItemServiceServer) UpdateItemLabels(context.Context, *UpdateItemLabelsRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateItemLabels not implemented")
}
func (UnimplementedItemServiceServer) UpdateItemLinks(context.Context, *UpdateItemLinksRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateItemLinks not implemented")
}
func (UnimplementedItemServiceServer) UpdateItemDueDate(context.Context, *UpdateItemDueDateRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateItemDueDate not implemented")
}
func (UnimplementedItemServiceServer) SetItemEffort(context.Context, *SetItemEffortRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method SetItemEffort not implemented")
}
func (UnimplementedItemServiceServer) ListLabels(context.Context, *ListLabelsRequest) (*ListLabelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLabels not implemented")
}
func (UnimplementedItemServiceServer) CreateLabel(context.Context, *CreateLabelRequest) (*Label, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLabel not implemented")
}
func (UnimplementedItemServiceServer) RenameLabel(context.Context, *RenameLabelRequest) (*Label, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameLabel not implemented")
}
func (UnimplementedItemServiceServer) DeleteLabel(context.Context, *DeleteLabelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLabel not implemented")
}
func (UnimplementedItemServiceServer) ListEfforts(context.Context, *ListEffortsRequest) (*ListEffortsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEfforts not implemented")
}
func (UnimplementedItemServiceServer) CreateEffort(context.Context, *CreateEffortRequest) (*Effort, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEffort not implemented")
}
func (UnimplementedItemServiceServer) RenameEffort(context.Context, *RenameEffortRequest) (*Effort, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameEffort not implemented")
}
func (UnimplementedItemServiceServer) DeleteEffort(context.Context, *DeleteEffortRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEffort not implemented")
}
func (UnimplementedItemServiceServer) ListBlockers(context.Context, *ListBlockersRequest) (*ListBlockersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlockers not implemented")
}
func (UnimplementedItemServiceServer) CreateBlocker(context.Context, *CreateBlockerRequest) (*Blocker, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBlocker not implemented")
}
func (UnimplementedItemServiceServer) UpdateBlocker(context.Context, *UpdateBlockerRequest) (*Blocker, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBlocker not implemented")
}
func (UnimplementedItemServiceServer) DeleteBlocker(context.Context, *DeleteBlockerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBlocker not implemented")
}
func (UnimplementedItemServiceServer) ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedItemServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*Comment, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedItemServiceServer) UpdateComment(context.Context, *UpdateCommentRequest) (*Comment, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedItemServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedItemServiceServer) mustEmbedUnimplementedItemServiceServer() {}
func (UnimplementedItemServiceServer) testEmbeddedByValue()                     {}

// UnsafeItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemServiceServer will
// result in compilation errors.
type UnsafeItemServiceServer interface {
	mustEmbedUnimplementedItemServiceServer()
}

func RegisterItemServiceServer(s grpc.ServiceRegistrar, srv ItemServiceServer) {
	// If the following call panics, it indicates UnimplementedItemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemService_ServiceDesc, srv)
}

func _ItemService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_CreateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_MoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).MoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_MoveItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).MoveItem(ctx, req.(*MoveItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_SetItemDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).SetItemDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_SetItemDone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).SetItemDone(ctx, req.(*SetItemDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_UpdateItemLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).UpdateItemLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_UpdateItemLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).UpdateItemLabels(ctx, req.(*UpdateItemLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_UpdateItemLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).UpdateItemLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_UpdateItemLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).UpdateItemLinks(ctx, req.(*UpdateItemLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_UpdateItemDueDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemDueDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).UpdateItemDueDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_UpdateItemDueDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).UpdateItemDueDate(ctx, req.(*UpdateItemDueDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_SetItemEffort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemEffortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).SetItemEffort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_SetItemEffort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).SetItemEffort(ctx, req.(*SetItemEffortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ListLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_ListLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListLabels(ctx, req.(*ListLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_CreateLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_CreateLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateLabel(ctx, req.(*CreateLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_RenameLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).RenameLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_RenameLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).RenameLabel(ctx, req.(*RenameLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_DeleteLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).DeleteLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_DeleteLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).DeleteLabel(ctx, req.(*DeleteLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ListEfforts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEffortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListEfforts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_ListEfforts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListEfforts(ctx, req.(*ListEffortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_CreateEffort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEffortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateEffort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_CreateEffort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateEffort(ctx, req.(*CreateEffortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_RenameEffort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameEffortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).RenameEffort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_RenameEffort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).RenameEffort(ctx, req.(*RenameEffortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_DeleteEffort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEffortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).DeleteEffort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_DeleteEffort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).DeleteEffort(ctx, req.(*DeleteEffortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ListBlockers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlockersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListBlockers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_ListBlockers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListBlockers(ctx, req.(*ListBlockersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_CreateBlocker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlockerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateBlocker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_CreateBlocker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateBlocker(ctx, req.(*CreateBlockerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_UpdateBlocker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlockerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).UpdateBlocker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_UpdateBlocker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).UpdateBlocker(ctx, req.(*UpdateBlockerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_DeleteBlocker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlockerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).DeleteBlocker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_DeleteBlocker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).DeleteBlocker(ctx, req.(*DeleteBlockerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemService_ServiceDesc is the grpc.ServiceDesc for ItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "item.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListItems",
			Handler:    _ItemService_ListItems_Handler,
		},
		{
			MethodName: "CreateItem",
			Handler:    _ItemService_CreateItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _ItemService_GetItem_Handler,
		},
		{
			MethodName: "MoveItem",
			Handler:    _ItemService_MoveItem_Handler,
		},
		{
			MethodName: "SetItemDone",
			Handler:    _ItemService_SetItemDone_Handler,
		},
		{
			MethodName: "UpdateItemLabels",
			Handler:    _ItemService_UpdateItemLabels_Handler,
		},
		{
			MethodName: "UpdateItemLinks",
			Handler:    _ItemService_UpdateItemLinks_Handler,
		},
		{
			MethodName: "UpdateItemDueDate",
			Handler:    _ItemService_UpdateItemDueDate_Handler,
		},
		{
			MethodName: "SetItemEffort",
			Handler:    _ItemService_SetItemEffort_Handler,
		},
		{
			MethodName: "ListLabels",
			Handler:    _ItemService_ListLabels_Handler,
		},
		{
			MethodName: "CreateLabel",
			Handler:    _ItemService_CreateLabel_Handler,
		},
		{
			MethodName: "RenameLabel",
			Handler:    _ItemService_RenameLabel_Handler,
		},
		{
			MethodName: "DeleteLabel",
			Handler:    _ItemService_DeleteLabel_Handler,
		},
		{
			MethodName: "ListEfforts",
			Handler:    _ItemService_ListEfforts_Handler,
		},
		{
			MethodName: "CreateEffort",
			Handler:    _ItemService_CreateEffort_Handler,
		},
		{
			MethodName: "RenameEffort",
			Handler:    _ItemService_RenameEffort_Handler,
		},
		{
			MethodName: "DeleteEffort",
			Handler:    _ItemService_DeleteEffort_Handler,
		},
		{
			MethodName: "ListBlockers",
			Handler:    _ItemService_ListBlockers_Handler,
		},
		{
			MethodName: "CreateBlocker",
			Handler:    _ItemService_CreateBlocker_Handler,
		},
		{
			MethodName: "UpdateBlocker",
			Handler:    _ItemService_UpdateBlocker_Handler,
		},
		{
			MethodName: "DeleteBlocker",
			Handler:    _ItemService_DeleteBlocker_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _ItemService_ListComments_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _ItemService_CreateComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _ItemService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _ItemService_DeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/item.proto",
}
