// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/item.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemView narrows ListItems to a single bucket. ITEM_VIEW_UNSPECIFIED keeps
// the legacy behaviour of returning both active and completed items.
type ItemView int32

const (
	ItemView_ITEM_VIEW_UNSPECIFIED ItemView = 0
	// UNTRIAGED: not done and carrying no manual ordering rank yet.
	ItemView_ITEM_VIEW_UNTRIAGED ItemView = 1
	// TRIAGED: not done and already placed in the manual order.
	ItemView_ITEM_VIEW_TRIAGED ItemView = 2
	// TIME_SENSITIVE: not done and carrying a due date.
	ItemView_ITEM_VIEW_TIME_SENSITIVE ItemView = 3
	// DONE: completed items.
	ItemView_ITEM_VIEW_DONE ItemView = 4
)

// Enum value maps for ItemView.
var (
	ItemView_name = map[int32]string{
		0: "ITEM_VIEW_UNSPECIFIED",
		1: "ITEM_VIEW_UNTRIAGED",
		2: "ITEM_VIEW_TRIAGED",
		3: "ITEM_VIEW_TIME_SENSITIVE",
		4: "ITEM_VIEW_DONE",
	}
	ItemView_value = map[string]int32{
		"ITEM_VIEW_UNSPECIFIED":    0,
		"ITEM_VIEW_UNTRIAGED":      1,
		"ITEM_VIEW_TRIAGED":        2,
		"ITEM_VIEW_TIME_SENSITIVE": 3,
		"ITEM_VIEW_DONE":           4,
	}
)

func (x ItemView) Enum() *ItemView {
	p := new(ItemView)
	*p = x
	return p
}

func (x ItemView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemView) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_item_proto_enumTypes[0].Descriptor()
}

func (ItemView) Type() protoreflect.EnumType {
	return &file_proto_item_proto_enumTypes[0]
}

func (x ItemView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemView.Descriptor instead.
func (ItemView) EnumDescriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{0}
}

// Label is a tag that can be attached to any number of items. Names are
// normalised to lower case with surrounding whitespace removed.
type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_proto_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Item is a single todo item.
type Item struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Done        bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	DueDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	ListId      *uint32                `protobuf:"varint,6,opt,name=list_id,json=listId,proto3,oneof" json:"list_id,omitempty"`
	// position is the manual ordering rank. It is set only while done is false.
	Position      *float64 `protobuf:"fixed64,7,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Labels        []*Label `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Item) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Item) GetListId() uint32 {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return 0
}

func (x *Item) GetPosition() float64 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *Item) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// labels restricts the result to items carrying every one of these labels.
	// An unknown name therefore yields no results.
	Labels []string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	// view narrows the result to a single bucket. Leaving it unset returns both
	// the active and completed items as before.
	View          ItemView `protobuf:"varint,2,opt,name=view,proto3,enum=item.ItemView" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_proto_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{2}
}

func (x *ListItemsRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListItemsRequest) GetView() ItemView {
	if x != nil {
		return x.View
	}
	return ItemView_ITEM_VIEW_UNSPECIFIED
}

type ListItemsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// active holds the items that are not yet done, in manual order.
	Active []*Item `protobuf:"bytes,1,rep,name=active,proto3" json:"active,omitempty"`
	// completed holds the done items, most recently updated first.
	Completed     []*Item `protobuf:"bytes,2,rep,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_proto_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{3}
}

func (x *ListItemsResponse) GetActive() []*Item {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *ListItemsResponse) GetCompleted() []*Item {
	if x != nil {
		return x.Completed
	}
	return nil
}

type CreateItemRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Title       string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DueDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	ListId      *uint32                `protobuf:"varint,4,opt,name=list_id,json=listId,proto3,oneof" json:"list_id,omitempty"`
	// labels are created on the fly when they do not exist yet.
	Labels        []string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_proto_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{4}
}

func (x *CreateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateItemRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *CreateItemRequest) GetListId() uint32 {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return 0
}

func (x *CreateItemRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MoveItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Exactly one anchor must be supplied.
	//
	// Types that are valid to be assigned to Anchor:
	//
	//	*MoveItemRequest_BeforeId
	//	*MoveItemRequest_AfterId
	Anchor isMoveItemRequest_Anchor `protobuf_oneof:"anchor"`
	// change_list reports whether list_id should be applied. It distinguishes
	// leaving the list untouched from clearing it.
	ChangeList bool `protobuf:"varint,4,opt,name=change_list,json=changeList,proto3" json:"change_list,omitempty"`
	// list_id is applied only when change_list is true. Leaving it unset while
	// change_list is true detaches the item from its list.
	ListId        *uint32 `protobuf:"varint,5,opt,name=list_id,json=listId,proto3,oneof" json:"list_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveItemRequest) Reset() {
	*x = MoveItemRequest{}
	mi := &file_proto_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveItemRequest) ProtoMessage() {}

func (x *MoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveItemRequest.ProtoReflect.Descriptor instead.
func (*MoveItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{5}
}

func (x *MoveItemRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MoveItemRequest) GetAnchor() isMoveItemRequest_Anchor {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *MoveItemRequest) GetBeforeId() uint32 {
	if x != nil {
		if x, ok := x.Anchor.(*MoveItemRequest_BeforeId); ok {
			return x.BeforeId
		}
	}
	return 0
}

func (x *MoveItemRequest) GetAfterId() uint32 {
	if x != nil {
		if x, ok := x.Anchor.(*MoveItemRequest_AfterId); ok {
			return x.AfterId
		}
	}
	return 0
}

func (x *MoveItemRequest) GetChangeList() bool {
	if x != nil {
		return x.ChangeList
	}
	return false
}

func (x *MoveItemRequest) GetListId() uint32 {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return 0
}

type isMoveItemRequest_Anchor interface {
	isMoveItemRequest_Anchor()
}

type MoveItemRequest_BeforeId struct {
	// before_id places the item immediately before the identified item.
	BeforeId uint32 `protobuf:"varint,2,opt,name=before_id,json=beforeId,proto3,oneof"`
}

type MoveItemRequest_AfterId struct {
	// after_id places the item immediately after the identified item.
	AfterId uint32 `protobuf:"varint,3,opt,name=after_id,json=afterId,proto3,oneof"`
}

func (*MoveItemRequest_BeforeId) isMoveItemRequest_Anchor() {}

func (*MoveItemRequest_AfterId) isMoveItemRequest_Anchor() {}

type SetItemDoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetItemDoneRequest) Reset() {
	*x = SetItemDoneRequest{}
	mi := &file_proto_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetItemDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemDoneRequest) ProtoMessage() {}

func (x *SetItemDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemDoneRequest.ProtoReflect.Descriptor instead.
func (*SetItemDoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{6}
}

func (x *SetItemDoneRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetItemDoneRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type UpdateItemLabelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// add names labels to attach, creating any that do not exist yet.
	Add []string `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty"`
	// remove names labels to detach. Names that are not known labels are
	// ignored rather than being created only to be detached again.
	Remove        []string `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemLabelsRequest) Reset() {
	*x = UpdateItemLabelsRequest{}
	mi := &file_proto_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemLabelsRequest) ProtoMessage() {}

func (x *UpdateItemLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemLabelsRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemLabelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateItemLabelsRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateItemLabelsRequest) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *UpdateItemLabelsRequest) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

type ListLabelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabelsRequest) Reset() {
	*x = ListLabelsRequest{}
	mi := &file_proto_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabelsRequest) ProtoMessage() {}

func (x *ListLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabelsRequest.ProtoReflect.Descriptor instead.
func (*ListLabelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{8}
}

type ListLabelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*Label               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabelsResponse) Reset() {
	*x = ListLabelsResponse{}
	mi := &file_proto_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabelsResponse) ProtoMessage() {}

func (x *ListLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabelsResponse.ProtoReflect.Descriptor instead.
func (*ListLabelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{9}
}

func (x *ListLabelsResponse) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLabelRequest) Reset() {
	*x = CreateLabelRequest{}
	mi := &file_proto_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLabelRequest) ProtoMessage() {}

func (x *CreateLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLabelRequest.ProtoReflect.Descriptor instead.
func (*CreateLabelRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{10}
}

func (x *CreateLabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RenameLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameLabelRequest) Reset() {
	*x = RenameLabelRequest{}
	mi := &file_proto_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameLabelRequest) ProtoMessage() {}

func (x *RenameLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameLabelRequest.ProtoReflect.Descriptor instead.
func (*RenameLabelRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{11}
}

func (x *RenameLabelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RenameLabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLabelRequest) Reset() {
	*x = DeleteLabelRequest{}
	mi := &file_proto_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLabelRequest) ProtoMessage() {}

func (x *DeleteLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLabelRequest.ProtoReflect.Descriptor instead.
func (*DeleteLabelRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteLabelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_item_proto protoreflect.FileDescriptor

const file_proto_item_proto_rawDesc = "" +
	"\n" +
	"\x10proto/item.proto\x12\x04item\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n" +
	"\x05Label\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa8\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12:\n" +
	"\bdue_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\adueDate\x88\x01\x01\x12\x1c\n" +
	"\alist_id\x18\x06 \x01(\rH\x01R\x06listId\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\a \x01(\x01H\x02R\bposition\x88\x01\x01\x12#\n" +
	"\x06labels\x18\b \x03(\v2\v.item.LabelR\x06labelsB\v\n" +
	"\t_due_dateB\n" +
	"\n" +
	"\b_list_idB\v\n" +
	"\t_position\"N\n" +
	"\x10ListItemsRequest\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\tR\x06labels\x12\"\n" +
	"\x04view\x18\x02 \x01(\x0e2\x0e.item.ItemViewR\x04view\"a\n" +
	"\x11ListItemsResponse\x12\"\n" +
	"\x06active\x18\x01 \x03(\v2\n" +
	".item.ItemR\x06active\x12(\n" +
	"\tcompleted\x18\x02 \x03(\v2\n" +
	".item.ItemR\tcompleted\"\xd6\x01\n" +
	"\x11CreateItemRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\bdue_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\adueDate\x88\x01\x01\x12\x1c\n" +
	"\alist_id\x18\x04 \x01(\rH\x01R\x06listId\x88\x01\x01\x12\x16\n" +
	"\x06labels\x18\x05 \x03(\tR\x06labelsB\v\n" +
	"\t_due_dateB\n" +
	"\n" +
	"\b_list_id\"\xb2\x01\n" +
	"\x0fMoveItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\tbefore_id\x18\x02 \x01(\rH\x00R\bbeforeId\x12\x1b\n" +
	"\bafter_id\x18\x03 \x01(\rH\x00R\aafterId\x12\x1f\n" +
	"\vchange_list\x18\x04 \x01(\bR\n" +
	"changeList\x12\x1c\n" +
	"\alist_id\x18\x05 \x01(\rH\x01R\x06listId\x88\x01\x01B\b\n" +
	"\x06anchorB\n" +
	"\n" +
	"\b_list_id\"8\n" +
	"\x12SetItemDoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\"S\n" +
	"\x17UpdateItemLabelsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03add\x18\x02 \x03(\tR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\"\x13\n" +
	"\x11ListLabelsRequest\"9\n" +
	"\x12ListLabelsResponse\x12#\n" +
	"\x06labels\x18\x01 \x03(\v2\v.item.LabelR\x06labels\"(\n" +
	"\x12CreateLabelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"8\n" +
	"\x12RenameLabelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"$\n" +
	"\x12DeleteLabelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id*\x87\x01\n" +
	"\bItemView\x12\x19\n" +
	"\x15ITEM_VIEW_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ITEM_VIEW_UNTRIAGED\x10\x01\x12\x15\n" +
	"\x11ITEM_VIEW_TRIAGED\x10\x02\x12\x1c\n" +
	"\x18ITEM_VIEW_TIME_SENSITIVE\x10\x03\x12\x12\n" +
	"\x0eITEM_VIEW_DONE\x10\x042\x8f\x04\n" +
	"\vItemService\x12<\n" +
	"\tListItems\x12\x16.item.ListItemsRequest\x1a\x17.item.ListItemsResponse\x121\n" +
	"\n" +
	"CreateItem\x12\x17.item.CreateItemRequest\x1a\n" +
	".item.Item\x12-\n" +
	"\bMoveItem\x12\x15.item.MoveItemRequest\x1a\n" +
	".item.Item\x123\n" +
	"\vSetItemDone\x12\x18.item.SetItemDoneRequest\x1a\n" +
	".item.Item\x12=\n" +
	"\x10UpdateItemLabels\x12\x1d.item.UpdateItemLabelsRequest\x1a\n" +
	".item.Item\x12?\n" +
	"\n" +
	"ListLabels\x12\x17.item.ListLabelsRequest\x1a\x18.item.ListLabelsResponse\x124\n" +
	"\vCreateLabel\x12\x18.item.CreateLabelRequest\x1a\v.item.Label\x124\n" +
	"\vRenameLabel\x12\x18.item.RenameLabelRequest\x1a\v.item.Label\x12?\n" +
	"\vDeleteLabel\x12\x18.item.DeleteLabelRequest\x1a\x16.google.protobuf.EmptyB$Z\"github.com/alexhokl/todo-cli/protob\x06proto3"

var (
	file_proto_item_proto_rawDescOnce sync.Once
	file_proto_item_proto_rawDescData []byte
)

func file_proto_item_proto_rawDescGZIP() []byte {
	file_proto_item_proto_rawDescOnce.Do(func() {
		file_proto_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_item_proto_rawDesc), len(file_proto_item_proto_rawDesc)))
	})
	return file_proto_item_proto_rawDescData
}

var file_proto_item_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_item_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_item_proto_goTypes = []any{
	(ItemView)(0),                   // 0: item.ItemView
	(*Label)(nil),                   // 1: item.Label
	(*Item)(nil),                    // 2: item.Item
	(*ListItemsRequest)(nil),        // 3: item.ListItemsRequest
	(*ListItemsResponse)(nil),       // 4: item.ListItemsResponse
	(*CreateItemRequest)(nil),       // 5: item.CreateItemRequest
	(*MoveItemRequest)(nil),         // 6: item.MoveItemRequest
	(*SetItemDoneRequest)(nil),      // 7: item.SetItemDoneRequest
	(*UpdateItemLabelsRequest)(nil), // 8: item.UpdateItemLabelsRequest
	(*ListLabelsRequest)(nil),       // 9: item.ListLabelsRequest
	(*ListLabelsResponse)(nil),      // 10: item.ListLabelsResponse
	(*CreateLabelRequest)(nil),      // 11: item.CreateLabelRequest
	(*RenameLabelRequest)(nil),      // 12: item.RenameLabelRequest
	(*DeleteLabelRequest)(nil),      // 13: item.DeleteLabelRequest
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 15: google.protobuf.Empty
}
var file_proto_item_proto_depIdxs = []int32{
	14, // 0: item.Item.due_date:type_name -> google.protobuf.Timestamp
	1,  // 1: item.Item.labels:type_name -> item.Label
	0,  // 2: item.ListItemsRequest.view:type_name -> item.ItemView
	2,  // 3: item.ListItemsResponse.active:type_name -> item.Item
	2,  // 4: item.ListItemsResponse.completed:type_name -> item.Item
	14, // 5: item.CreateItemRequest.due_date:type_name -> google.protobuf.Timestamp
	1,  // 6: item.ListLabelsResponse.labels:type_name -> item.Label
	3,  // 7: item.ItemService.ListItems:input_type -> item.ListItemsRequest
	5,  // 8: item.ItemService.CreateItem:input_type -> item.CreateItemRequest
	6,  // 9: item.ItemService.MoveItem:input_type -> item.MoveItemRequest
	7,  // 10: item.ItemService.SetItemDone:input_type -> item.SetItemDoneRequest
	8,  // 11: item.ItemService.UpdateItemLabels:input_type -> item.UpdateItemLabelsRequest
	9,  // 12: item.ItemService.ListLabels:input_type -> item.ListLabelsRequest
	11, // 13: item.ItemService.CreateLabel:input_type -> item.CreateLabelRequest
	12, // 14: item.ItemService.RenameLabel:input_type -> item.RenameLabelRequest
	13, // 15: item.ItemService.DeleteLabel:input_type -> item.DeleteLabelRequest
	4,  // 16: item.ItemService.ListItems:output_type -> item.ListItemsResponse
	2,  // 17: item.ItemService.CreateItem:output_type -> item.Item
	2,  // 18: item.ItemService.MoveItem:output_type -> item.Item
	2,  // 19: item.ItemService.SetItemDone:output_type -> item.Item
	2,  // 20: item.ItemService.UpdateItemLabels:output_type -> item.Item
	10, // 21: item.ItemService.ListLabels:output_type -> item.ListLabelsResponse
	1,  // 22: item.ItemService.CreateLabel:output_type -> item.Label
	1,  // 23: item.ItemService.RenameLabel:output_type -> item.Label
	15, // 24: item.ItemService.DeleteLabel:output_type -> google.protobuf.Empty
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_item_proto_init() }
func file_proto_item_proto_init() {
	if File_proto_item_proto != nil {
		return
	}
	file_proto_item_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_item_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_item_proto_msgTypes[5].OneofWrappers = []any{
		(*MoveItemRequest_BeforeId)(nil),
		(*MoveItemRequest_AfterId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_item_proto_rawDesc), len(file_proto_item_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_item_proto_goTypes,
		DependencyIndexes: file_proto_item_proto_depIdxs,
		EnumInfos:         file_proto_item_proto_enumTypes,
		MessageInfos:      file_proto_item_proto_msgTypes,
	}.Build()
	File_proto_item_proto = out.File
	file_proto_item_proto_goTypes = nil
	file_proto_item_proto_depIdxs = nil
}
