// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/item.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemService_ListItems_FullMethodName        = "/item.ItemService/ListItems"
	ItemService_CreateItem_FullMethodName       = "/item.ItemService/CreateItem"
	ItemService_MoveItem_FullMethodName         = "/item.ItemService/MoveItem"
	ItemService_SetItemDone_FullMethodName      = "/item.ItemService/SetItemDone"
	ItemService_UpdateItemLabels_FullMethodName = "/item.ItemService/UpdateItemLabels"
	ItemService_SetItemEffort_FullMethodName    = "/item.ItemService/SetItemEffort"
	ItemService_ListLabels_FullMethodName       = "/item.ItemService/ListLabels"
	ItemService_CreateLabel_FullMethodName      = "/item.ItemService/CreateLabel"
	ItemService_RenameLabel_FullMethodName      = "/item.ItemService/RenameLabel"
	ItemService_DeleteLabel_FullMethodName      = "/item.ItemService/DeleteLabel"
	ItemService_ListEfforts_FullMethodName      = "/item.ItemService/ListEfforts"
	ItemService_CreateEffort_FullMethodName     = "/item.ItemService/CreateEffort"
	ItemService_RenameEffort_FullMethodName     = "/item.ItemService/RenameEffort"
	ItemService_DeleteEffort_FullMethodName     = "/item.ItemService/DeleteEffort"
)

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ItemService is the gRPC API served by `todo serve`. RPCs are added here and
// registered in cmd/serve.go.
type ItemServiceClient interface {
	// ListItems returns the active items in their manual order along with the
	// completed items ordered by how recently they were updated.
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	// CreateItem appends a new item to the end of the manual order.
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*Item, error)
	// MoveItem places an item immediately before or after another item and
	// optionally reassigns its list in the same operation.
	MoveItem(ctx context.Context, in *MoveItemRequest, opts ...grpc.CallOption) (*Item, error)
	// SetItemDone completes or reopens an item. Completing removes it from the
	// manual order; reopening appends it to the end.
	SetItemDone(ctx context.Context, in *SetItemDoneRequest, opts ...grpc.CallOption) (*Item, error)
	// UpdateItemLabels attaches and detaches labels on an item. Labels being
	// added are created on the fly when they do not exist yet.
	UpdateItemLabels(ctx context.Context, in *UpdateItemLabelsRequest, opts ...grpc.CallOption) (*Item, error)
	// SetItemEffort attaches an effort to an item by name, or clears it when the
	// name is empty. The effort must already exist; unknown names are reported.
	SetItemEffort(ctx context.Context, in *SetItemEffortRequest, opts ...grpc.CallOption) (*Item, error)
	// ListLabels returns every known label ordered by name.
	ListLabels(ctx context.Context, in *ListLabelsRequest, opts ...grpc.CallOption) (*ListLabelsResponse, error)
	// CreateLabel creates a label explicitly and reports a name that is already
	// taken rather than returning the existing label.
	CreateLabel(ctx context.Context, in *CreateLabelRequest, opts ...grpc.CallOption) (*Label, error)
	// RenameLabel changes the name of an existing label.
	RenameLabel(ctx context.Context, in *RenameLabelRequest, opts ...grpc.CallOption) (*Label, error)
	// DeleteLabel removes a label that is no longer attached to any item.
	DeleteLabel(ctx context.Context, in *DeleteLabelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListEfforts returns every known effort ordered by name.
	ListEfforts(ctx context.Context, in *ListEffortsRequest, opts ...grpc.CallOption) (*ListEffortsResponse, error)
	// CreateEffort creates an effort explicitly and reports a name that is
	// already taken rather than returning the existing effort.
	CreateEffort(ctx context.Context, in *CreateEffortRequest, opts ...grpc.CallOption) (*Effort, error)
	// RenameEffort changes the name of an existing effort.
	RenameEffort(ctx context.Context, in *RenameEffortRequest, opts ...grpc.CallOption) (*Effort, error)
	// DeleteEffort removes an effort that is no longer attached to any item.
	DeleteEffort(ctx context.Context, in *DeleteEffortRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type itemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemServiceClient(cc grpc.ClientConnInterface) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, ItemService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_CreateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) MoveItem(ctx context.Context, in *MoveItemRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_MoveItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) SetItemDone(ctx context.Context, in *SetItemDoneRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_SetItemDone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) UpdateItemLabels(ctx context.Context, in *UpdateItemLabelsRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_UpdateItemLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) SetItemEffort(ctx context.Context, in *SetItemEffortRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ItemService_SetItemEffort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ListLabels(ctx context.Context, in *ListLabelsRequest, opts ...grpc.CallOption) (*ListLabelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLabelsResponse)
	err := c.cc.Invoke(ctx, ItemService_ListLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) CreateLabel(ctx context.Context, in *CreateLabelRequest, opts ...grpc.CallOption) (*Label, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Label)
	err := c.cc.Invoke(ctx, ItemService_CreateLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) RenameLabel(ctx context.Context, in *RenameLabelRequest, opts ...grpc.CallOption) (*Label, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Label)
	err := c.cc.Invoke(ctx, ItemService_RenameLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) DeleteLabel(ctx context.Context, in *DeleteLabelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ItemService_DeleteLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ListEfforts(ctx context.Context, in *ListEffortsRequest, opts ...grpc.CallOption) (*ListEffortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEffortsResponse)
	err := c.cc.Invoke(ctx, ItemService_ListEfforts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) CreateEffort(ctx context.Context, in *CreateEffortRequest, opts ...grpc.CallOption) (*Effort, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Effort)
	err := c.cc.Invoke(ctx, ItemService_CreateEffort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) RenameEffort(ctx context.Context, in *RenameEffortRequest, opts ...grpc.CallOption) (*Effort, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Effort)
	err := c.cc.Invoke(ctx, ItemService_RenameEffort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) DeleteEffort(ctx context.Context, in *DeleteEffortRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ItemService_DeleteEffort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
// All implementations must embed UnimplementedItemServiceServer
// for forward compatibility.
//
// ItemService is the gRPC API served by `todo serve`. RPCs are added here and
// registered in cmd/serve.go.
type ItemServiceServer interface {
	// ListItems returns the active items in their manual order along with the
	// completed items ordered by how recently they were updated.
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	// CreateItem appends a new item to the end of the manual order.
	CreateItem(context.Context, *CreateItemRequest) (*Item, error)
	// MoveItem places an item immediately before or after another item and
	// optionally reassigns its list in the same operation.
	MoveItem(context.Context, *MoveItemRequest) (*Item, error)
	// SetItemDone completes or reopens an item. Completing removes it from the
	// manual order; reopening appends it to the end.
	SetItemDone(context.Context, *SetItemDoneRequest) (*Item, error)
	// UpdateItemLabels attaches and detaches labels on an item. Labels being
	// added are created on the fly when they do not exist yet.
	UpdateItemLabels(context.Context, *UpdateItemLabelsRequest) (*Item, error)
	// SetItemEffort attaches an effort to an item by name, or clears it when the
	// name is empty. The effort must already exist; unknown names are reported.
	SetItemEffort(context.Context, *SetItemEffortRequest) (*Item, error)
	// ListLabels returns every known label ordered by name.
	ListLabels(context.Context, *ListLabelsRequest) (*ListLabelsResponse, error)
	// CreateLabel creates a label explicitly and reports a name that is already
	// taken rather than returning the existing label.
	CreateLabel(context.Context, *CreateLabelRequest) (*Label, error)
	// RenameLabel changes the name of an existing label.
	RenameLabel(context.Context, *RenameLabelRequest) (*Label, error)
	// DeleteLabel removes a label that is no longer attached to any item.
	DeleteLabel(context.Context, *DeleteLabelRequest) (*emptypb.Empty, error)
	// ListEfforts returns every known effort ordered by name.
	ListEfforts(context.Context, *ListEffortsRequest) (*ListEffortsResponse, error)
	// CreateEffort creates an effort explicitly and reports a name that is
	// already taken rather than returning the existing effort.
	CreateEffort(context.Context, *CreateEffortRequest) (*Effort, error)
	// RenameEffort changes the name of an existing effort.
	RenameEffort(context.Context, *RenameEffortRequest) (*Effort, error)
	// DeleteEffort removes an effort that is no longer attached to any item.
	DeleteEffort(context.Context, *DeleteEffortRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedItemServiceServer()
}

// UnimplementedItemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemServiceServer struct{}

func (UnimplementedItemServiceServer) ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedItemServiceServer) CreateItem(context.Context, *CreateItemRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedItemServiceServer) MoveItem(context.Context, *MoveItemRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveItem not implemented")
}
func (UnimplementedItemServiceServer) SetItemDone(context.Context, *SetItemDoneRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method SetItemDone not implemented")
}
func (UnimplementedItemServiceServer) UpdateItemLabels(context.Context, *UpdateItemLabelsRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateItemLabels not implemented")
}
func (UnimplementedItemServiceServer) SetItemEffort(context.Context, *SetItemEffortRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method SetItemEffort not implemented")
}
func (UnimplementedItemServiceServer) ListLabels(context.Context, *ListLabelsRequest) (*ListLabelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLabels not implemented")
}
func (UnimplementedItemServiceServer) CreateLabel(context.Context, *CreateLabelRequest) (*Label, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLabel not implemented")
}
func (UnimplementedItemServiceServer) RenameLabel(context.Context, *RenameLabelRequest) (*Label, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameLabel not implemented")
}
func (UnimplementedItemServiceServer) DeleteLabel(context.Context, *DeleteLabelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLabel not implemented")
}
func (UnimplementedItemServiceServer) ListEfforts(context.Context, *ListEffortsRequest) (*ListEffortsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEfforts not implemented")
}
func (UnimplementedItemServiceServer) CreateEffort(context.Context, *CreateEffortRequest) (*Effort, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEffort not implemented")
}
func (UnimplementedItemServiceServer) RenameEffort(context.Context, *RenameEffortRequest) (*Effort, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameEffort not implemented")
}
func (UnimplementedItemServiceServer) DeleteEffort(context.Context, *DeleteEffortRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEffort not implemented")
}
func (UnimplementedItemServiceServer) mustEmbedUnimplementedItemServiceServer() {}
func (UnimplementedItemServiceServer) testEmbeddedByValue()                     {}

// UnsafeItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemServiceServer will
// result in compilation errors.
type UnsafeItemServiceServer interface {
	mustEmbedUnimplementedItemServiceServer()
}

func RegisterItemServiceServer(s grpc.ServiceRegistrar, srv ItemServiceServer) {
	// If the following call panics, it indicates UnimplementedItemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemService_ServiceDesc, srv)
}

func _ItemService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_CreateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_MoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).MoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_MoveItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).MoveItem(ctx, req.(*MoveItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_SetItemDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).SetItemDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_SetItemDone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).SetItemDone(ctx, req.(*SetItemDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_UpdateItemLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).UpdateItemLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_UpdateItemLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).UpdateItemLabels(ctx, req.(*UpdateItemLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_SetItemEffort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemEffortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).SetItemEffort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_SetItemEffort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).SetItemEffort(ctx, req.(*SetItemEffortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ListLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_ListLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListLabels(ctx, req.(*ListLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_CreateLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_CreateLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateLabel(ctx, req.(*CreateLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_RenameLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).RenameLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_RenameLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).RenameLabel(ctx, req.(*RenameLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_DeleteLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).DeleteLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_DeleteLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).DeleteLabel(ctx, req.(*DeleteLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ListEfforts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEffortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListEfforts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_ListEfforts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListEfforts(ctx, req.(*ListEffortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_CreateEffort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEffortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateEffort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_CreateEffort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateEffort(ctx, req.(*CreateEffortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_RenameEffort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameEffortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).RenameEffort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_RenameEffort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).RenameEffort(ctx, req.(*RenameEffortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_DeleteEffort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEffortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).DeleteEffort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemService_DeleteEffort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).DeleteEffort(ctx, req.(*DeleteEffortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemService_ServiceDesc is the grpc.ServiceDesc for ItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "item.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListItems",
			Handler:    _ItemService_ListItems_Handler,
		},
		{
			MethodName: "CreateItem",
			Handler:    _ItemService_CreateItem_Handler,
		},
		{
			MethodName: "MoveItem",
			Handler:    _ItemService_MoveItem_Handler,
		},
		{
			MethodName: "SetItemDone",
			Handler:    _ItemService_SetItemDone_Handler,
		},
		{
			MethodName: "UpdateItemLabels",
			Handler:    _ItemService_UpdateItemLabels_Handler,
		},
		{
			MethodName: "SetItemEffort",
			Handler:    _ItemService_SetItemEffort_Handler,
		},
		{
			MethodName: "ListLabels",
			Handler:    _ItemService_ListLabels_Handler,
		},
		{
			MethodName: "CreateLabel",
			Handler:    _ItemService_CreateLabel_Handler,
		},
		{
			MethodName: "RenameLabel",
			Handler:    _ItemService_RenameLabel_Handler,
		},
		{
			MethodName: "DeleteLabel",
			Handler:    _ItemService_DeleteLabel_Handler,
		},
		{
			MethodName: "ListEfforts",
			Handler:    _ItemService_ListEfforts_Handler,
		},
		{
			MethodName: "CreateEffort",
			Handler:    _ItemService_CreateEffort_Handler,
		},
		{
			MethodName: "RenameEffort",
			Handler:    _ItemService_RenameEffort_Handler,
		},
		{
			MethodName: "DeleteEffort",
			Handler:    _ItemService_DeleteEffort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/item.proto",
}
