// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/todo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Label is a tag that can be attached to any number of todos. Names are
// normalised to lower case with surrounding whitespace removed.
type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_proto_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Todo is a single todo item.
type Todo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Done        bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	DueDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	ListId      *uint32                `protobuf:"varint,6,opt,name=list_id,json=listId,proto3,oneof" json:"list_id,omitempty"`
	// position is the manual ordering rank. It is set only while done is false.
	Position      *float64 `protobuf:"fixed64,7,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Labels        []*Label `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_proto_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{1}
}

func (x *Todo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Todo) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Todo) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Todo) GetListId() uint32 {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return 0
}

func (x *Todo) GetPosition() float64 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *Todo) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListTodosRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// labels restricts the result to todos carrying every one of these labels.
	// An unknown name therefore yields no results.
	Labels        []string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_proto_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosRequest.ProtoReflect.Descriptor instead.
func (*ListTodosRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{2}
}

func (x *ListTodosRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListTodosResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// active holds the todos that are not yet done, in manual order.
	Active []*Todo `protobuf:"bytes,1,rep,name=active,proto3" json:"active,omitempty"`
	// completed holds the done todos, most recently updated first.
	Completed     []*Todo `protobuf:"bytes,2,rep,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosResponse) Reset() {
	*x = ListTodosResponse{}
	mi := &file_proto_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosResponse) ProtoMessage() {}

func (x *ListTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosResponse.ProtoReflect.Descriptor instead.
func (*ListTodosResponse) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{3}
}

func (x *ListTodosResponse) GetActive() []*Todo {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *ListTodosResponse) GetCompleted() []*Todo {
	if x != nil {
		return x.Completed
	}
	return nil
}

type CreateTodoRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Title       string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DueDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	ListId      *uint32                `protobuf:"varint,4,opt,name=list_id,json=listId,proto3,oneof" json:"list_id,omitempty"`
	// labels are created on the fly when they do not exist yet.
	Labels        []string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_proto_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTodoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTodoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTodoRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *CreateTodoRequest) GetListId() uint32 {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return 0
}

func (x *CreateTodoRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MoveTodoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Exactly one anchor must be supplied.
	//
	// Types that are valid to be assigned to Anchor:
	//
	//	*MoveTodoRequest_BeforeId
	//	*MoveTodoRequest_AfterId
	Anchor isMoveTodoRequest_Anchor `protobuf_oneof:"anchor"`
	// change_list reports whether list_id should be applied. It distinguishes
	// leaving the list untouched from clearing it.
	ChangeList bool `protobuf:"varint,4,opt,name=change_list,json=changeList,proto3" json:"change_list,omitempty"`
	// list_id is applied only when change_list is true. Leaving it unset while
	// change_list is true detaches the todo from its list.
	ListId        *uint32 `protobuf:"varint,5,opt,name=list_id,json=listId,proto3,oneof" json:"list_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveTodoRequest) Reset() {
	*x = MoveTodoRequest{}
	mi := &file_proto_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTodoRequest) ProtoMessage() {}

func (x *MoveTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTodoRequest.ProtoReflect.Descriptor instead.
func (*MoveTodoRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{5}
}

func (x *MoveTodoRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MoveTodoRequest) GetAnchor() isMoveTodoRequest_Anchor {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *MoveTodoRequest) GetBeforeId() uint32 {
	if x != nil {
		if x, ok := x.Anchor.(*MoveTodoRequest_BeforeId); ok {
			return x.BeforeId
		}
	}
	return 0
}

func (x *MoveTodoRequest) GetAfterId() uint32 {
	if x != nil {
		if x, ok := x.Anchor.(*MoveTodoRequest_AfterId); ok {
			return x.AfterId
		}
	}
	return 0
}

func (x *MoveTodoRequest) GetChangeList() bool {
	if x != nil {
		return x.ChangeList
	}
	return false
}

func (x *MoveTodoRequest) GetListId() uint32 {
	if x != nil && x.ListId != nil {
		return *x.ListId
	}
	return 0
}

type isMoveTodoRequest_Anchor interface {
	isMoveTodoRequest_Anchor()
}

type MoveTodoRequest_BeforeId struct {
	// before_id places the todo immediately before the identified todo.
	BeforeId uint32 `protobuf:"varint,2,opt,name=before_id,json=beforeId,proto3,oneof"`
}

type MoveTodoRequest_AfterId struct {
	// after_id places the todo immediately after the identified todo.
	AfterId uint32 `protobuf:"varint,3,opt,name=after_id,json=afterId,proto3,oneof"`
}

func (*MoveTodoRequest_BeforeId) isMoveTodoRequest_Anchor() {}

func (*MoveTodoRequest_AfterId) isMoveTodoRequest_Anchor() {}

type SetTodoDoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTodoDoneRequest) Reset() {
	*x = SetTodoDoneRequest{}
	mi := &file_proto_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTodoDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTodoDoneRequest) ProtoMessage() {}

func (x *SetTodoDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTodoDoneRequest.ProtoReflect.Descriptor instead.
func (*SetTodoDoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{6}
}

func (x *SetTodoDoneRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetTodoDoneRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type UpdateTodoLabelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// add names labels to attach, creating any that do not exist yet.
	Add []string `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty"`
	// remove names labels to detach. Names that are not known labels are
	// ignored rather than being created only to be detached again.
	Remove        []string `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoLabelsRequest) Reset() {
	*x = UpdateTodoLabelsRequest{}
	mi := &file_proto_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoLabelsRequest) ProtoMessage() {}

func (x *UpdateTodoLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoLabelsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoLabelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTodoLabelsRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTodoLabelsRequest) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *UpdateTodoLabelsRequest) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

type ListLabelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabelsRequest) Reset() {
	*x = ListLabelsRequest{}
	mi := &file_proto_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabelsRequest) ProtoMessage() {}

func (x *ListLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabelsRequest.ProtoReflect.Descriptor instead.
func (*ListLabelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{8}
}

type ListLabelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*Label               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabelsResponse) Reset() {
	*x = ListLabelsResponse{}
	mi := &file_proto_todo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabelsResponse) ProtoMessage() {}

func (x *ListLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabelsResponse.ProtoReflect.Descriptor instead.
func (*ListLabelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{9}
}

func (x *ListLabelsResponse) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLabelRequest) Reset() {
	*x = CreateLabelRequest{}
	mi := &file_proto_todo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLabelRequest) ProtoMessage() {}

func (x *CreateLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLabelRequest.ProtoReflect.Descriptor instead.
func (*CreateLabelRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{10}
}

func (x *CreateLabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RenameLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameLabelRequest) Reset() {
	*x = RenameLabelRequest{}
	mi := &file_proto_todo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameLabelRequest) ProtoMessage() {}

func (x *RenameLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameLabelRequest.ProtoReflect.Descriptor instead.
func (*RenameLabelRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{11}
}

func (x *RenameLabelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RenameLabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLabelRequest) Reset() {
	*x = DeleteLabelRequest{}
	mi := &file_proto_todo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLabelRequest) ProtoMessage() {}

func (x *DeleteLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLabelRequest.ProtoReflect.Descriptor instead.
func (*DeleteLabelRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteLabelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_todo_proto protoreflect.FileDescriptor

const file_proto_todo_proto_rawDesc = "" +
	"\n" +
	"\x10proto/todo.proto\x12\x04todo\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n" +
	"\x05Label\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa8\x02\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12:\n" +
	"\bdue_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\adueDate\x88\x01\x01\x12\x1c\n" +
	"\alist_id\x18\x06 \x01(\rH\x01R\x06listId\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\a \x01(\x01H\x02R\bposition\x88\x01\x01\x12#\n" +
	"\x06labels\x18\b \x03(\v2\v.todo.LabelR\x06labelsB\v\n" +
	"\t_due_dateB\n" +
	"\n" +
	"\b_list_idB\v\n" +
	"\t_position\"*\n" +
	"\x10ListTodosRequest\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\tR\x06labels\"a\n" +
	"\x11ListTodosResponse\x12\"\n" +
	"\x06active\x18\x01 \x03(\v2\n" +
	".todo.TodoR\x06active\x12(\n" +
	"\tcompleted\x18\x02 \x03(\v2\n" +
	".todo.TodoR\tcompleted\"\xd6\x01\n" +
	"\x11CreateTodoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\bdue_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\adueDate\x88\x01\x01\x12\x1c\n" +
	"\alist_id\x18\x04 \x01(\rH\x01R\x06listId\x88\x01\x01\x12\x16\n" +
	"\x06labels\x18\x05 \x03(\tR\x06labelsB\v\n" +
	"\t_due_dateB\n" +
	"\n" +
	"\b_list_id\"\xb2\x01\n" +
	"\x0fMoveTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\tbefore_id\x18\x02 \x01(\rH\x00R\bbeforeId\x12\x1b\n" +
	"\bafter_id\x18\x03 \x01(\rH\x00R\aafterId\x12\x1f\n" +
	"\vchange_list\x18\x04 \x01(\bR\n" +
	"changeList\x12\x1c\n" +
	"\alist_id\x18\x05 \x01(\rH\x01R\x06listId\x88\x01\x01B\b\n" +
	"\x06anchorB\n" +
	"\n" +
	"\b_list_id\"8\n" +
	"\x12SetTodoDoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\"S\n" +
	"\x17UpdateTodoLabelsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03add\x18\x02 \x03(\tR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\"\x13\n" +
	"\x11ListLabelsRequest\"9\n" +
	"\x12ListLabelsResponse\x12#\n" +
	"\x06labels\x18\x01 \x03(\v2\v.todo.LabelR\x06labels\"(\n" +
	"\x12CreateLabelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"8\n" +
	"\x12RenameLabelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"$\n" +
	"\x12DeleteLabelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id2\x8f\x04\n" +
	"\vTodoService\x12<\n" +
	"\tListTodos\x12\x16.todo.ListTodosRequest\x1a\x17.todo.ListTodosResponse\x121\n" +
	"\n" +
	"CreateTodo\x12\x17.todo.CreateTodoRequest\x1a\n" +
	".todo.Todo\x12-\n" +
	"\bMoveTodo\x12\x15.todo.MoveTodoRequest\x1a\n" +
	".todo.Todo\x123\n" +
	"\vSetTodoDone\x12\x18.todo.SetTodoDoneRequest\x1a\n" +
	".todo.Todo\x12=\n" +
	"\x10UpdateTodoLabels\x12\x1d.todo.UpdateTodoLabelsRequest\x1a\n" +
	".todo.Todo\x12?\n" +
	"\n" +
	"ListLabels\x12\x17.todo.ListLabelsRequest\x1a\x18.todo.ListLabelsResponse\x124\n" +
	"\vCreateLabel\x12\x18.todo.CreateLabelRequest\x1a\v.todo.Label\x124\n" +
	"\vRenameLabel\x12\x18.todo.RenameLabelRequest\x1a\v.todo.Label\x12?\n" +
	"\vDeleteLabel\x12\x18.todo.DeleteLabelRequest\x1a\x16.google.protobuf.EmptyB$Z\"github.com/alexhokl/todo-cli/protob\x06proto3"

var (
	file_proto_todo_proto_rawDescOnce sync.Once
	file_proto_todo_proto_rawDescData []byte
)

func file_proto_todo_proto_rawDescGZIP() []byte {
	file_proto_todo_proto_rawDescOnce.Do(func() {
		file_proto_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_todo_proto_rawDesc), len(file_proto_todo_proto_rawDesc)))
	})
	return file_proto_todo_proto_rawDescData
}

var file_proto_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_todo_proto_goTypes = []any{
	(*Label)(nil),                   // 0: todo.Label
	(*Todo)(nil),                    // 1: todo.Todo
	(*ListTodosRequest)(nil),        // 2: todo.ListTodosRequest
	(*ListTodosResponse)(nil),       // 3: todo.ListTodosResponse
	(*CreateTodoRequest)(nil),       // 4: todo.CreateTodoRequest
	(*MoveTodoRequest)(nil),         // 5: todo.MoveTodoRequest
	(*SetTodoDoneRequest)(nil),      // 6: todo.SetTodoDoneRequest
	(*UpdateTodoLabelsRequest)(nil), // 7: todo.UpdateTodoLabelsRequest
	(*ListLabelsRequest)(nil),       // 8: todo.ListLabelsRequest
	(*ListLabelsResponse)(nil),      // 9: todo.ListLabelsResponse
	(*CreateLabelRequest)(nil),      // 10: todo.CreateLabelRequest
	(*RenameLabelRequest)(nil),      // 11: todo.RenameLabelRequest
	(*DeleteLabelRequest)(nil),      // 12: todo.DeleteLabelRequest
	(*timestamppb.Timestamp)(nil),   // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 14: google.protobuf.Empty
}
var file_proto_todo_proto_depIdxs = []int32{
	13, // 0: todo.Todo.due_date:type_name -> google.protobuf.Timestamp
	0,  // 1: todo.Todo.labels:type_name -> todo.Label
	1,  // 2: todo.ListTodosResponse.active:type_name -> todo.Todo
	1,  // 3: todo.ListTodosResponse.completed:type_name -> todo.Todo
	13, // 4: todo.CreateTodoRequest.due_date:type_name -> google.protobuf.Timestamp
	0,  // 5: todo.ListLabelsResponse.labels:type_name -> todo.Label
	2,  // 6: todo.TodoService.ListTodos:input_type -> todo.ListTodosRequest
	4,  // 7: todo.TodoService.CreateTodo:input_type -> todo.CreateTodoRequest
	5,  // 8: todo.TodoService.MoveTodo:input_type -> todo.MoveTodoRequest
	6,  // 9: todo.TodoService.SetTodoDone:input_type -> todo.SetTodoDoneRequest
	7,  // 10: todo.TodoService.UpdateTodoLabels:input_type -> todo.UpdateTodoLabelsRequest
	8,  // 11: todo.TodoService.ListLabels:input_type -> todo.ListLabelsRequest
	10, // 12: todo.TodoService.CreateLabel:input_type -> todo.CreateLabelRequest
	11, // 13: todo.TodoService.RenameLabel:input_type -> todo.RenameLabelRequest
	12, // 14: todo.TodoService.DeleteLabel:input_type -> todo.DeleteLabelRequest
	3,  // 15: todo.TodoService.ListTodos:output_type -> todo.ListTodosResponse
	1,  // 16: todo.TodoService.CreateTodo:output_type -> todo.Todo
	1,  // 17: todo.TodoService.MoveTodo:output_type -> todo.Todo
	1,  // 18: todo.TodoService.SetTodoDone:output_type -> todo.Todo
	1,  // 19: todo.TodoService.UpdateTodoLabels:output_type -> todo.Todo
	9,  // 20: todo.TodoService.ListLabels:output_type -> todo.ListLabelsResponse
	0,  // 21: todo.TodoService.CreateLabel:output_type -> todo.Label
	0,  // 22: todo.TodoService.RenameLabel:output_type -> todo.Label
	14, // 23: todo.TodoService.DeleteLabel:output_type -> google.protobuf.Empty
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_todo_proto_init() }
func file_proto_todo_proto_init() {
	if File_proto_todo_proto != nil {
		return
	}
	file_proto_todo_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_todo_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_todo_proto_msgTypes[5].OneofWrappers = []any{
		(*MoveTodoRequest_BeforeId)(nil),
		(*MoveTodoRequest_AfterId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_todo_proto_rawDesc), len(file_proto_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_todo_proto_goTypes,
		DependencyIndexes: file_proto_todo_proto_depIdxs,
		MessageInfos:      file_proto_todo_proto_msgTypes,
	}.Build()
	File_proto_todo_proto = out.File
	file_proto_todo_proto_goTypes = nil
	file_proto_todo_proto_depIdxs = nil
}
