// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/todo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TodoService_ListTodos_FullMethodName        = "/todo.TodoService/ListTodos"
	TodoService_CreateTodo_FullMethodName       = "/todo.TodoService/CreateTodo"
	TodoService_MoveTodo_FullMethodName         = "/todo.TodoService/MoveTodo"
	TodoService_SetTodoDone_FullMethodName      = "/todo.TodoService/SetTodoDone"
	TodoService_UpdateTodoLabels_FullMethodName = "/todo.TodoService/UpdateTodoLabels"
	TodoService_ListLabels_FullMethodName       = "/todo.TodoService/ListLabels"
	TodoService_CreateLabel_FullMethodName      = "/todo.TodoService/CreateLabel"
	TodoService_RenameLabel_FullMethodName      = "/todo.TodoService/RenameLabel"
	TodoService_DeleteLabel_FullMethodName      = "/todo.TodoService/DeleteLabel"
)

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TodoService is the gRPC API served by `todo serve`. RPCs are added here and
// registered in cmd/serve.go.
type TodoServiceClient interface {
	// ListTodos returns the active todos in their manual order along with the
	// completed todos ordered by how recently they were updated.
	ListTodos(ctx context.Context, in *ListTodosRequest, opts ...grpc.CallOption) (*ListTodosResponse, error)
	// CreateTodo appends a new todo to the end of the manual order.
	CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*Todo, error)
	// MoveTodo places a todo immediately before or after another todo and
	// optionally reassigns its list in the same operation.
	MoveTodo(ctx context.Context, in *MoveTodoRequest, opts ...grpc.CallOption) (*Todo, error)
	// SetTodoDone completes or reopens a todo. Completing removes it from the
	// manual order; reopening appends it to the end.
	SetTodoDone(ctx context.Context, in *SetTodoDoneRequest, opts ...grpc.CallOption) (*Todo, error)
	// UpdateTodoLabels attaches and detaches labels on a todo. Labels being
	// added are created on the fly when they do not exist yet.
	UpdateTodoLabels(ctx context.Context, in *UpdateTodoLabelsRequest, opts ...grpc.CallOption) (*Todo, error)
	// ListLabels returns every known label ordered by name.
	ListLabels(ctx context.Context, in *ListLabelsRequest, opts ...grpc.CallOption) (*ListLabelsResponse, error)
	// CreateLabel creates a label explicitly and reports a name that is already
	// taken rather than returning the existing label.
	CreateLabel(ctx context.Context, in *CreateLabelRequest, opts ...grpc.CallOption) (*Label, error)
	// RenameLabel changes the name of an existing label.
	RenameLabel(ctx context.Context, in *RenameLabelRequest, opts ...grpc.CallOption) (*Label, error)
	// DeleteLabel removes a label that is no longer attached to any todo.
	DeleteLabel(ctx context.Context, in *DeleteLabelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type todoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoServiceClient(cc grpc.ClientConnInterface) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) ListTodos(ctx context.Context, in *ListTodosRequest, opts ...grpc.CallOption) (*ListTodosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTodosResponse)
	err := c.cc.Invoke(ctx, TodoService_ListTodos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*Todo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Todo)
	err := c.cc.Invoke(ctx, TodoService_CreateTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) MoveTodo(ctx context.Context, in *MoveTodoRequest, opts ...grpc.CallOption) (*Todo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Todo)
	err := c.cc.Invoke(ctx, TodoService_MoveTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) SetTodoDone(ctx context.Context, in *SetTodoDoneRequest, opts ...grpc.CallOption) (*Todo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Todo)
	err := c.cc.Invoke(ctx, TodoService_SetTodoDone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) UpdateTodoLabels(ctx context.Context, in *UpdateTodoLabelsRequest, opts ...grpc.CallOption) (*Todo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Todo)
	err := c.cc.Invoke(ctx, TodoService_UpdateTodoLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) ListLabels(ctx context.Context, in *ListLabelsRequest, opts ...grpc.CallOption) (*ListLabelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLabelsResponse)
	err := c.cc.Invoke(ctx, TodoService_ListLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) CreateLabel(ctx context.Context, in *CreateLabelRequest, opts ...grpc.CallOption) (*Label, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Label)
	err := c.cc.Invoke(ctx, TodoService_CreateLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) RenameLabel(ctx context.Context, in *RenameLabelRequest, opts ...grpc.CallOption) (*Label, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Label)
	err := c.cc.Invoke(ctx, TodoService_RenameLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DeleteLabel(ctx context.Context, in *DeleteLabelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TodoService_DeleteLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
// All implementations must embed UnimplementedTodoServiceServer
// for forward compatibility.
//
// TodoService is the gRPC API served by `todo serve`. RPCs are added here and
// registered in cmd/serve.go.
type TodoServiceServer interface {
	// ListTodos returns the active todos in their manual order along with the
	// completed todos ordered by how recently they were updated.
	ListTodos(context.Context, *ListTodosRequest) (*ListTodosResponse, error)
	// CreateTodo appends a new todo to the end of the manual order.
	CreateTodo(context.Context, *CreateTodoRequest) (*Todo, error)
	// MoveTodo places a todo immediately before or after another todo and
	// optionally reassigns its list in the same operation.
	MoveTodo(context.Context, *MoveTodoRequest) (*Todo, error)
	// SetTodoDone completes or reopens a todo. Completing removes it from the
	// manual order; reopening appends it to the end.
	SetTodoDone(context.Context, *SetTodoDoneRequest) (*Todo, error)
	// UpdateTodoLabels attaches and detaches labels on a todo. Labels being
	// added are created on the fly when they do not exist yet.
	UpdateTodoLabels(context.Context, *UpdateTodoLabelsRequest) (*Todo, error)
	// ListLabels returns every known label ordered by name.
	ListLabels(context.Context, *ListLabelsRequest) (*ListLabelsResponse, error)
	// CreateLabel creates a label explicitly and reports a name that is already
	// taken rather than returning the existing label.
	CreateLabel(context.Context, *CreateLabelRequest) (*Label, error)
	// RenameLabel changes the name of an existing label.
	RenameLabel(context.Context, *RenameLabelRequest) (*Label, error)
	// DeleteLabel removes a label that is no longer attached to any todo.
	DeleteLabel(context.Context, *DeleteLabelRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedTodoServiceServer()
}

// UnimplementedTodoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTodoServiceServer struct{}

func (UnimplementedTodoServiceServer) ListTodos(context.Context, *ListTodosRequest) (*ListTodosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTodos not implemented")
}
func (UnimplementedTodoServiceServer) CreateTodo(context.Context, *CreateTodoRequest) (*Todo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTodo not implemented")
}
func (UnimplementedTodoServiceServer) MoveTodo(context.Context, *MoveTodoRequest) (*Todo, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveTodo not implemented")
}
func (UnimplementedTodoServiceServer) SetTodoDone(context.Context, *SetTodoDoneRequest) (*Todo, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTodoDone not implemented")
}
func (UnimplementedTodoServiceServer) UpdateTodoLabels(context.Context, *UpdateTodoLabelsRequest) (*Todo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTodoLabels not implemented")
}
func (UnimplementedTodoServiceServer) ListLabels(context.Context, *ListLabelsRequest) (*ListLabelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLabels not implemented")
}
func (UnimplementedTodoServiceServer) CreateLabel(context.Context, *CreateLabelRequest) (*Label, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLabel not implemented")
}
func (UnimplementedTodoServiceServer) RenameLabel(context.Context, *RenameLabelRequest) (*Label, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameLabel not implemented")
}
func (UnimplementedTodoServiceServer) DeleteLabel(context.Context, *DeleteLabelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLabel not implemented")
}
func (UnimplementedTodoServiceServer) mustEmbedUnimplementedTodoServiceServer() {}
func (UnimplementedTodoServiceServer) testEmbeddedByValue()                     {}

// UnsafeTodoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoServiceServer will
// result in compilation errors.
type UnsafeTodoServiceServer interface {
	mustEmbedUnimplementedTodoServiceServer()
}

func RegisterTodoServiceServer(s grpc.ServiceRegistrar, srv TodoServiceServer) {
	// If the following call panics, it indicates UnimplementedTodoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TodoService_ServiceDesc, srv)
}

func _TodoService_ListTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTodosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ListTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoService_ListTodos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ListTodos(ctx, req.(*ListTodosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoService_CreateTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateTodo(ctx, req.(*CreateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_MoveTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).MoveTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoService_MoveTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).MoveTodo(ctx, req.(*MoveTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_SetTodoDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTodoDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).SetTodoDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoService_SetTodoDone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).SetTodoDone(ctx, req.(*SetTodoDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_UpdateTodoLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodoLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).UpdateTodoLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoService_UpdateTodoLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).UpdateTodoLabels(ctx, req.(*UpdateTodoLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_ListLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ListLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoService_ListLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ListLabels(ctx, req.(*ListLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_CreateLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoService_CreateLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateLabel(ctx, req.(*CreateLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_RenameLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).RenameLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoService_RenameLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).RenameLabel(ctx, req.(*RenameLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DeleteLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).DeleteLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoService_DeleteLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).DeleteLabel(ctx, req.(*DeleteLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoService_ServiceDesc is the grpc.ServiceDesc for TodoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todo.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTodos",
			Handler:    _TodoService_ListTodos_Handler,
		},
		{
			MethodName: "CreateTodo",
			Handler:    _TodoService_CreateTodo_Handler,
		},
		{
			MethodName: "MoveTodo",
			Handler:    _TodoService_MoveTodo_Handler,
		},
		{
			MethodName: "SetTodoDone",
			Handler:    _TodoService_SetTodoDone_Handler,
		},
		{
			MethodName: "UpdateTodoLabels",
			Handler:    _TodoService_UpdateTodoLabels_Handler,
		},
		{
			MethodName: "ListLabels",
			Handler:    _TodoService_ListLabels_Handler,
		},
		{
			MethodName: "CreateLabel",
			Handler:    _TodoService_CreateLabel_Handler,
		},
		{
			MethodName: "RenameLabel",
			Handler:    _TodoService_RenameLabel_Handler,
		},
		{
			MethodName: "DeleteLabel",
			Handler:    _TodoService_DeleteLabel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/todo.proto",
}
